Repository KSP-CKAN/NetKAN, pull requests merged in 2018-11, with the labels that each got.

#6791 CTTP - Remote hosting of NetKAN metadata
  NetKAN/CommunityTerrainTexturePack.netkan
Labels: Blocked-on-CKAN-Feature

#6809 Add TheWorldBeyond - Full
  NetKAN/TheWorldBeyond.netkan
Labels: Discussion needed

#6818 Add SciFiVE
  NetKAN/SciFiVisualEnhancements.netkan
Labels: Blocked-on-Mod-Author

#6827 SpaceDock catch-up 4
  NetKAN/DunaDirect.netkan
  NetKAN/LandOJunk.netkan
  NetKAN/NGC3371-Skybox.netkan
Labels: Blocked-on-CKAN-Feature, Easy

#6849 Require specific Scatterer for RSSVE
  NetKAN/RSSVE-HR.netkan
  NetKAN/RSSVE-LR.netkan
Labels: Fix relationships

#6850 SpaceDock catch-up 5
  NetKAN/AATI-Flags.netkan
  NetKAN/AdvancedTextures.netkan
  NetKAN/DeclasseVoodooCar.netkan
  NetKAN/MilkyWay-Skybox.netkan
  NetKAN/PureElectricEngines.netkan
  NetKAN/SpaceXLandingPad.netkan
  NetKAN/StockalikeUtilityVehicles.netkan
  NetKAN/WoodSpaceProgram.netkan
Labels: Blocked-on-Dependency
