Repository KSP-CKAN/NetKAN, pull requests merged in 2018-03, with the labels that each got.

#5762 Add 6.4x scale 12.8x distance from SpaceDock
  NetKAN/64xscale128xdistance.netkan
Labels: Blocked-on-Other

#6336 Add Kerbalism Continued
  NetKAN/Kerbalism.netkan
Labels: Ready to Merge

#6333 Update IR ModelRework
  NetKAN/IR-Model-Rework-Core.frozen
  NetKAN/IR-Model-Rework-Core.netkan
  NetKAN/IR-Model-Rework-Expansion.frozen
  NetKAN/IR-Model-Rework-Expansion.netkan
  NetKAN/IR-Model-Rework-Utility.frozen
  NetKAN/IR-Model-Rework-Utility.netkan
Labels: Blocked-on-Dependency

#6401 Add Telemachus Continued from SpaceDock
  NetKAN/TelemachusContinued.netkan
Labels: Blocked-on-Mod-Author
