Repository KSP-CKAN/NetKAN, pull requests merged in 2019-12, with the labels that each got.

#7542 Add tags to the 32 most popular mods
  NetKAN/B9-props.netkan
  NetKAN/B9.netkan
  NetKAN/B9AerospaceHX.netkan
  NetKAN/B9AerospaceLegacy.netkan
  NetKAN/CommunityResourcePack.netkan
  NetKAN/EnvironmentalVisualEnhancements-HR.netkan
  NetKAN/EnvironmentalVisualEnhancements.netkan
  NetKAN/Firespitter.netkan
  NetKAN/FirespitterCore.netkan
  NetKAN/FirespitterResourcesConfig.netkan
  NetKAN/InterstellarFuelSwitch-Core.netkan
  NetKAN/InterstellarFuelSwitch.netkan
  NetKAN/KerbalAlarmClock.netkan
  NetKAN/KerbalEngineerRedux.netkan
  NetKAN/KerbalJointReinforcementContinued.netkan
  NetKAN/NearFutureSolar-Core.netkan
  NetKAN/NearFutureSolar.netkan
  NetKAN/ProceduralFairings.netkan
  NetKAN/RasterPropMonitor-Core.netkan
  NetKAN/RasterPropMonitor.netkan
  NetKAN/RealSolarSystem.netkan
  NetKAN/SCANsat.netkan
  NetKAN/SVE-HighResolution.netkan
  NetKAN/SVE-LowResolution.netkan
  NetKAN/SVE-MediumResolution.netkan
  NetKAN/SVE-Scatterer-Config.netkan
  NetKAN/SVE-Sunflare.netkan
  NetKAN/SVE-Terrain.netkan
  NetKAN/Scatterer-config.netkan
  NetKAN/Scatterer-sunflare.netkan
  NetKAN/Scatterer.netkan
  NetKAN/StockVisualEnhancements.netkan
Labels: Easy, Pull request

#7541 Add Grannus Expansion Pack
  NetKAN/GrannusExpansionPack-CommNet.netkan
  NetKAN/GrannusExpansionPack-JNSQ.netkan
  NetKAN/GrannusExpansionPack-Primary.netkan
  NetKAN/GrannusExpansionPack.netkan
Labels: Mod-request, Pull request

#7546 Update Kerbalism conflicts and tags
  NetKAN/Kerbalism.netkan
Labels: Fix relationships, Pull request

#7558 Tag and de-metanetkan HebaruSan's mods
  NetKAN/Astrogator.netkan
  NetKAN/Ringworld.netkan
  NetKAN/SmartTank.netkan
Labels: Easy, Pull request

#7540 Add Nibiru System from SpaceDock
  NetKAN/NibiruSystem.netkan
Labels: Blocked-on-Other

#7569 Removed deplyment of seperate folder for InterstellarHybridRocketry
  NetKAN/KSPInterstellarExtended.netkan
Labels: Needs more info
