Repository KSP-CKAN/NetKAN, pull requests merged in 2019-06, with the labels that each got.

#7224 Update AstronomersVisualPack.netkan
  NetKAN/AstronomersVisualPack.netkan
Labels: Waiting on PR creator

#6521 Add Kabrams Sun Flare's Pack for Scatterer. from SpaceDock
  NetKAN/KabramsSunFlaresPack-Blue-High.netkan
  NetKAN/KabramsSunFlaresPack-Blue-Low.netkan
  NetKAN/KabramsSunFlaresPack-Blue-Medium.netkan
  NetKAN/KabramsSunFlaresPack-Diamond-High.netkan
  NetKAN/KabramsSunFlaresPack-Diamond-Low.netkan
  NetKAN/KabramsSunFlaresPack-Diamond-Medium.netkan
  NetKAN/KabramsSunFlaresPack-Green-High.netkan
  NetKAN/KabramsSunFlaresPack-Green-Low.netkan
  NetKAN/KabramsSunFlaresPack-Green-Medium.netkan
  NetKAN/KabramsSunFlaresPack-Orange-High.netkan
  NetKAN/KabramsSunFlaresPack-Orange-Low.netkan
  NetKAN/KabramsSunFlaresPack-Orange-Medium.netkan
  NetKAN/KabramsSunFlaresPack-Red-High.netkan
  NetKAN/KabramsSunFlaresPack-Red-Low.netkan
  NetKAN/KabramsSunFlaresPack-Red-Medium.netkan
  NetKAN/KabramsSunFlaresPack-White-High.netkan
  NetKAN/KabramsSunFlaresPack-White-Low.netkan
  NetKAN/KabramsSunFlaresPack-White-Medium.netkan
Labels: Blocked-on-Other

#7116 Add Whirligig World from SpaceDock
  NetKAN/WhirligigWorld.netkan
Labels: Blocked-on-Dependency
