Repository KSP-CKAN/NetKAN, pull requests merged in 2019-11, with the labels that each got.

#7482 Fix spec_versions
  NetKAN/PartOverhaulsSETI.netkan
  NetKAN/SETI-BalanceMod.netkan
  NetKAN/SETI-CareerChallenge.netkan
  NetKAN/SETI-CustomBarnKit.netkan
  NetKAN/SETI-ProbeControlEnabler.netkan
  NetKAN/SETI-RebalanceMaterialsGoo.netkan
  NetKAN/SETI-RemoteTech.netkan
  NetKAN/UnmannedBeforeManned.netkan
  NetKAN/UnmannedBeforeMannedChallenge.netkan
Labels: Easy, Pull request

#6877 Add PolandBall from SpaceDock
  NetKAN/PolandBall.netkan
Labels: Blocked-on-Other

#7488 Set Unlicense for applicable mods
  NetKAN/ContractConfigurator-SCANsat.netkan
  NetKAN/ControlLock.netkan
  NetKAN/CoolRockets.netkan
  NetKAN/EasyVesselSwitch.netkan
  NetKAN/ExceptionDetector.netkan
  NetKAN/KScale2.netkan
  NetKAN/LayeredAnimations.netkan
  NetKAN/NavBallsToYou.netkan
  NetKAN/ReflectionPlugin.netkan
  NetKAN/StockNoContracts.netkan
  NetKAN/StockPlugins.netkan
  NetKAN/StockRT.netkan
  NetKAN/StockSCANsat.netkan
Labels: Fix license

#7490 Add DoubleTapBrakes
  NetKAN/DoubleTapBrakes.netkan
Labels: Easy, Mod-request, Pull request

#7505 Add Contract Pack: CommNet Relays
  NetKAN/ContractConfigurator-CommNetRelays.netkan
Labels: Easy, Mod-request, Pull request

#7503 Prune redundant author lists
  NetKAN/BurnTogetherContinued.netkan
  NetKAN/DestructionEffects.netkan
  NetKAN/DistantObject-default.netkan
  NetKAN/DistantObject.netkan
  NetKAN/FerramAerospaceResearchContinued.netkan
  NetKAN/GravityTurnContinued.netkan
  NetKAN/HangarExtender.frozen
  NetKAN/KerbalEngineerRedux.netkan
  NetKAN/KerbalFlightIndicators.netkan
  NetKAN/MapResourceOverlay.netkan
  NetKAN/NehemiahEngineeringOrbitalScience.netkan
  NetKAN/PilotAssistant.netkan
  NetKAN/PlanetShine-Config-Default.netkan
  NetKAN/PlanetShine.netkan
  NetKAN/RCSLandAid.netkan
  NetKAN/Science-Full-Reward.netkan
  NetKAN/SemiSaturatableRW.netkan
  NetKAN/TWR1.netkan
  NetKAN/VenStockRevamp-Core.netkan
  NetKAN/VenStockRevamp-NewParts.netkan
  NetKAN/VenStockRevamp.netkan
  NetKAN/VesselMoverContinued.netkan
  NetKAN/VesselSwitcher.netkan
Labels: Easy, In progress, Pull request

#7511 Make ChattererExtended indefinitely compatible
  NetKAN/ChattererExtended.netkan
Labels: Blocked-on-Mod-Author, Discussion needed, Easy, Fix compatibility, Pull request

#7528 Set x_netkan_allow_out_of_order for backporting mods
  NetKAN/Backports/Kopernicus.netkan
  NetKAN/KSPInterstellarExtended.netkan
Labels: Easy, Pull request
