Repository KSP-CKAN/NetKAN, pull requests merged in 2019-03, with the labels that each got.

#7058 Fix bad min version syntax
  NetKAN/IR-Model-Rework-Core.netkan
  NetKAN/IR-Model-Rework-Expansion.netkan
  NetKAN/IR-Model-Rework-Utility.netkan
  NetKAN/SentarExpansion.netkan
Labels: Easy, Fix relationships

#7062 DMagic Orbital Science recommendation changed from US1 to US2
  NetKAN/DMagicOrbitalScience.netkan
Labels: Fix relationships

#7065 Update NKRsDEM.netkan
  NetKAN/NKRsDEM.netkan
Labels: Fix install

#7092 Add missing Near Future dependencies
  NetKAN/NearFutureConstruction.netkan
  NetKAN/NearFutureSolar.netkan
Labels: Fix relationships
