Repository KSP-CKAN/NetKAN, pull requests merged in 2019-10, with the labels that each got.

#7417 Add More Hitchhikers from SpaceDock
  NetKAN/MoreHitchhikers.netkan
Labels: Blocked-on-Other, Mod-request

#7419 Normalize install_to paths
  NetKAN/BlacklegIndustriesMMTantaresTACLS.netkan
  NetKAN/CommunityPartsTitlesExtrasNoCCKDup.netkan
  NetKAN/OinkersSkybox.netkan
  NetKAN/VersatileToolboxSystem-TACLSPack.netkan
  NetKAN/VersatileToolboxSystem-USIPack.netkan
Labels: Bug, Easy, Fix install, Pull request

#7399 Add three requested mods
  NetKAN/ContractConfigurator-CareerEvolution.netkan
  NetKAN/ContractConfigurator-CommNetRelays.frozen
  NetKAN/Interkosmos.frozen
Labels: Blocked-on-Mod-Author

#7435 Add MADLAD
  NetKAN/MADLAD.netkan
Labels: Blocked-on-Mod-Author, Easy, Pull request

#7438 Override Firespitter 7.13's max KSP version to 1.7
  NetKAN/Firespitter.netkan
  NetKAN/FirespitterCore.netkan
  NetKAN/FirespitterResourcesConfig.netkan
Labels: Fix compatibiltiy, Needs looking into, Pull request

#7445 Add RationalResourcesParts
  NetKAN/RationalResourcesParts.netkan
Labels: Easy, Pull request
