Repository KSP-CKAN/NetKAN, pull requests merged in 2020-09, with the labels that each got.

#8128 Add ContractConfigurator dependency to TestFlight
  NetKAN/TestFlight.netkan
Labels: Fix relationships, Pull request

#8145 New homepage for new EVE fork
  NetKAN/EnvironmentalVisualEnhancements.netkan
Labels: Easy, Pull request

#8146 Fix ULAVulcan install
  NetKAN/ULAVulcan.netkan
Labels: Fix install

#8165 Add vref to NextStarIndustries
  NetKAN/NextStarIndustries.netkan
Labels: Easy
