Repository KSP-CKAN/NetKAN, pull requests merged in 2020-05, with the labels that each got.

#7875 Override ProbeControlRoom compatibility
  NetKAN/ProbeControlRoom.netkan
Labels: Fix compatibility

#7876 Use GitHub version numbers for AstronomersVisualPack
  NetKAN/AstronomersVisualPack.netkan
Labels: Pull request

#7877 Add PAWRangeBuff
  NetKAN/PAWRangeBuff.netkan
Labels: Mod-request

#7878 Update ModularFuelTanks to 5.13.1
  NetKAN/ModularFuelTanks.netkan
Labels: Easy, Pull request

#7883 Add TweakScale depends to InterstellarFuelSwitch-Core
  NetKAN/InterstellarFuelSwitch-Core.netkan
  NetKAN/InterstellarFuelSwitch.netkan
Labels: Easy, Fix relationships, In progress, Pull request

#7873 Add SSTO Project from SpaceDock
  NetKAN/SSTOProject.netkan
Labels: In progress

#7888 Adding TweakScale Companion for ReStock+ into CKAN.
  NetKAN/TweakScaleCompanion-ReStockPlus.netkan
Labels: Pull request

#7891 Sort and fix Spectra NetKAN Provides/conflicts/depends/suggests/rec
  NetKAN/Spectra.netkan
Labels: Fix compatibility, Fix relationships, In progress, Pull request

#7901 Fix HooliganLabsAirships install
  NetKAN/HooliganLabsAirships.netkan
Labels: Easy, Fix install, Pull request

#7909 Make ASETProps compatible with all game versions
  NetKAN/ASETProps.netkan
Labels: Easy, Fix compatibility, Pull request

#7907 Add ModuleManager depends for third pass of mods using MM syntax
  NetKAN/ASETProps.netkan
  NetKAN/AbovetheSkySoyuzTMAandR7.netkan
  NetKAN/Airlocks.netkan
  NetKAN/AlmostRealSolarSystem.netkan
  NetKAN/AlphaMensaeMobileLauncher.netkan
  NetKAN/AutomatedAerialRefueling.netkan
  NetKAN/AutomaticFuelCells.netkan
  NetKAN/BackInBlackTexturePack.netkan
  NetKAN/BetterBurnTime.netkan
  NetKAN/BonVoyage.netkan
  NetKAN/BuoyancyControl.netkan
  NetKAN/CAMk3BlockII.netkan
  NetKAN/CVX.netkan
  NetKAN/CapsuleCorporationEndeavourMarsBaseCamp.netkan
  NetKAN/ChakaMonkeyExplorationSystems.netkan
  NetKAN/ControlSurfaceToggle.netkan
  NetKAN/CxAerospace.netkan
  NetKAN/DeepSkyCore.netkan
  NetKAN/DerivativeTextures.netkan
  NetKAN/EVATransfer.netkan
  NetKAN/Explainer.netkan
  NetKAN/FlexibleDocking.netkan
  NetKAN/GreenSkullRevived.netkan
  NetKAN/HooliganLabsAirships.netkan
  NetKAN/HydrogenCompression.netkan
  NetKAN/IONRCS.netkan
  NetKAN/IndicatorLightsCommunityExtensions.netkan
  NetKAN/InterKalactic2.netkan
  NetKAN/InternalRCS.netkan
  NetKAN/JPL-RSS.netkan
  NetKAN/JSat.netkan
  NetKAN/JX2Antenna.netkan
  NetKAN/JackOLantern.netkan
  NetKAN/JoolBiomes.netkan
  NetKAN/K2CommandPodCont.netkan
  NetKAN/KA330InflatableSpaceHotel.netkan
  NetKAN/KEAMKerbalExpandableActivityModule.netkan
  NetKAN/KerbalField.netkan
  NetKAN/KerbalGalacticExpansion.netkan
  NetKAN/KerbalModsOverhaul.netkan
  NetKAN/KerbalScienceInnovation.netkan
  NetKAN/Kerbalized-SpaceX.netkan
  NetKAN/KerbalowAerospace.netkan
  NetKAN/imkSushisPlanetSystem.netkan
Labels: Easy, Fix compatibility, Pull request

#7911 Add ModuleManager depends for fourth pass of mods using MM syntax
  NetKAN/Contares-Common.netkan
  NetKAN/Contares.netkan
  NetKAN/KKsDeltaPack.netkan
  NetKAN/KOOSE.netkan
  NetKAN/KerbinRoverOffRoadVehicles.netkan
  NetKAN/KerbobulusSpaceIndustriesMiscellaneousPartsDivision.netkan
  NetKAN/KrakenScience.netkan
  NetKAN/LargeBoatPartsPack.netkan
  NetKAN/Leviathanclass.netkan
  NetKAN/MiporiaPlanetPack.netkan
  NetKAN/MkerbIncScienceInstruments.netkan
  NetKAN/MoS-AeronauticDepartment.netkan
  NetKAN/ModularLaunchPads.netkan
  NetKAN/ModularPods.netkan
  NetKAN/ModularRocketSystemsLITE.netkan
  NetKAN/NKRsDEM.netkan
  NetKAN/OPTUSILifeSupportPatch.netkan
  NetKAN/OrbitalColony.netkan
  NetKAN/PhoenixIndustriesSpaceTug.netkan
  NetKAN/PlanetaryDomes.netkan
  NetKAN/PureElectricEngines.netkan
  NetKAN/RealEngines.netkan
  NetKAN/RealSolarSystemExpanded-UnofficialPatch.netkan
  NetKAN/SeparatorDestroyer.netkan
  NetKAN/ShadowWorksStockalikeSLSandMore.netkan
  NetKAN/SpaceOpera.netkan
  NetKAN/StockalikeMiningExtension.netkan
  NetKAN/StockishProjectOrion.netkan
  NetKAN/Switch-All.netkan
  NetKAN/TDIndustriesRCSandHypergolicengines.netkan
  NetKAN/TantaresAndBDBNowinColors.netkan
  NetKAN/TheMartianforKSP.netkan
  NetKAN/ThorTech.netkan
  NetKAN/USAFOrionMod-TD-subedition.netkan
  NetKAN/VentralDrill.netkan
  NetKAN/notes.netkan
Labels: Easy, Fix relationships, Pull request

#7912 Add vrefs to first group of mods with version files
  NetKAN/AirplanePlus.netkan
  NetKAN/AutoLoadGame.netkan
  NetKAN/BonVoyage.netkan
  NetKAN/CEDA-Aethon-ITS.netkan
  NetKAN/CelestialBodyScienceEditor.netkan
  NetKAN/ChakaMonkeyExplorationSystems.netkan
  NetKAN/ContractConfigurator-ContractPackHistoricalProgression.netkan
  NetKAN/ContractConfigurator-KSI.netkan
  NetKAN/ContractRewardModifier.netkan
  NetKAN/CorrectCoL.netkan
  NetKAN/DavonSupplyMod.netkan
  NetKAN/DeepSkyCore.netkan
  NetKAN/DraggableNavball.netkan
  NetKAN/ESLDJumpBeacons.netkan
  NetKAN/EVATransfer.netkan
  NetKAN/ExceptionDetectorUpdated.netkan
  NetKAN/FanRadiator.netkan
Labels: Easy, Fix compatibility, Pull request

#7914 Add vrefs to third group of mods with version files
  NetKAN/KWSKerbalWeaponsSystem.netkan
  NetKAN/KerbalModsOverhaul.netkan
  NetKAN/LCAproject.netkan
  NetKAN/ModularRocketSystemsLITE.netkan
  NetKAN/MoonReorganizer.netkan
  NetKAN/NAS.netkan
  NetKAN/OPTUSILifeSupportPatch.netkan
  NetKAN/PL-IRC.netkan
  NetKAN/PL-KSat.netkan
  NetKAN/ShipSaveSplicer.netkan
  NetKAN/SpaceBus.netkan
  NetKAN/StockishProjectOrion.netkan
  NetKAN/TheRATPack.netkan
  NetKAN/ThorTech.netkan
  NetKAN/TooManyOrbits.netkan
  NetKAN/TreeToppler.netkan
  NetKAN/VesselView-UI-RasterPropMonitor.netkan
  NetKAN/VesselView-UI-Toolbar.netkan
  NetKAN/VesselView.netkan
  NetKAN/WhoAmI.netkan
  NetKAN/WorldStabilizer.netkan
  NetKAN/Wwwwwwwww.netkan
  NetKAN/notes.netkan
  NetKAN/xScience.netkan
Labels: Fix compatibility

#7918 Fix PlanetWiki find regex and epoch, move contents to own folder
  NetKAN/PlanetWiki.netkan
Labels: Fix install, Fix versioning

#7919 Fix SpaceXLaunchVehicles install and recommends
  NetKAN/SpaceXLaunchVehicles.netkan
Labels: Easy, Fix install, Fix relationships, Pull request

#7920 Add depends for ZZZRadioTelescope
  NetKAN/ZZZRadioTelescope.netkan
Labels: Easy, Fix relationships, Pull request

#7921 Remove hardcoded ksp_version from SeparatorDestroyer
  NetKAN/SeparatorDestroyer.netkan
Labels: Fix compatibility

#7924 Remove outdated LanderCanMk12 dependencies
  NetKAN/LanderCanMk12.netkan
Labels: Fix relationships

#7926 Add PayToPlay
  NetKAN/PayToPlay.netkan
Labels: Mod-request, Pull request

#7922 Adding LisiasT's KSP-Recall to CKAN
  NetKAN/KSP-Recall.netkan
Labels: Blocked-on-Other

#7931 Remove unnecessary ModuleManager depends
  NetKAN/BOPN.netkan
  NetKAN/BasicProceduralTextures.netkan
  NetKAN/CEDA-AeronauticsDivision.netkan
  NetKAN/CEDA-Aethon-ITS.netkan
  NetKAN/CameraTools.netkan
  NetKAN/ContractConfigurator-ContractPackHistoricalProgression.netkan
  NetKAN/ContractConfigurator-FarOutContracts.netkan
  NetKAN/CriticalTemperatureGauge.netkan
  NetKAN/DecalStickers.netkan
  NetKAN/DuoPods.netkan
  NetKAN/FanRadiator.netkan
  NetKAN/FlatBtmShtlSys.netkan
  NetKAN/Insight.netkan
  NetKAN/JDLiquidFuelCell.netkan
  NetKAN/KerbalActuators.netkan
  NetKAN/KerbalHotSeatCont.netkan
  NetKAN/KerbalKonstructs.netkan
  NetKAN/Kerbalism.netkan
  NetKAN/LudicrousPropulsionSystems.netkan
  NetKAN/MSP3000.netkan
  NetKAN/NovaPunchRebalanced-Freyja.netkan
  NetKAN/NovaPunchRebalanced-Odin.netkan
  NetKAN/NovaPunchRebalanced-Thor.netkan
  NetKAN/ORIONMonkeyBusinessIncParts.netkan
  NetKAN/PatentPurchase.netkan
  NetKAN/PlayYourWay.netkan
  NetKAN/ProceduralParts-Textures-BattleTechAerospace.netkan
  NetKAN/ROLib.netkan
  NetKAN/SigmaSciDefRenamer.netkan
  NetKAN/TRR-Guide.netkan
  NetKAN/TRR-MyTextureMod.netkan
  NetKAN/TestFlight.netkan
  NetKAN/TestFlightConfigStock.netkan
  NetKAN/TextureReplacerReplaced.netkan
  NetKAN/TexturesUnlimited.netkan
  NetKAN/VenStockRevamp-NewParts.netkan
  NetKAN/Wraithforge.netkan
  NetKAN/newReactionWheels.netkan
Labels: Easy, Fix relationships, Pull request

#7932 Get KourageousTourists compat info from version file
  NetKAN/KourageousTourists.netkan
Labels: Easy, Fix compatibility, Pull request

#7904 Add SuperBattery
  NetKAN/SuperBattery.netkan
Labels: Blocked-on-Other, Easy, Mod-request, Pull request

#7933 Freeze archived mods
  NetKAN/B9-PWings-Modified.frozen
  NetKAN/ExtendedAntennaProgression.frozen
  NetKAN/KSPAPIExtensions.frozen
  NetKAN/KerbolPlus.frozen
  NetKAN/KittopiaTech.frozen
Labels: Easy, Pull request

#7940 Add ModuleManager depends for sixth pass of mods using MM syntax
  NetKAN/JanitorsCloset.netkan
  NetKAN/KerbalActuators.netkan
Labels: Easy, Fix relationships, Pull request

#7942 Fix ExplorationPlus install path
  NetKAN/ContractConfigurator-ExplorationPlus.netkan
Labels: Easy, Fix install, Pull request

#7941 Update Whirligig World dependencies
  NetKAN/SciRev.netkan
  NetKAN/WhirligigWorld.netkan
Labels: Blocked-on-Dependency, Easy, Fix relationships, Pull request

#7943 Fix CollisionFXReUpdated install stanza
  NetKAN/CollisionFXReUpdated.netkan
Labels: Fix install

#7945 Fix CST100Starliner install
  NetKAN/CST100Starliner.netkan
Labels: Fix install, Pull request

#7947 Mark WhirligigWorld as providing EVE config
  NetKAN/WhirligigWorld.netkan
Labels: Bug, Easy, Fix relationships, Pull request

#7949 Remove unnecessary vrefs
  NetKAN/KScale2.netkan
  NetKAN/OPTSpacePlaneMain.netkan
  NetKAN/SSRSS-Rescale.netkan
  NetKAN/newReactionWheels.netkan
Labels: Easy, Pull request
