Repository KSP-CKAN/NetKAN, pull requests merged in 2020-07, with the labels that each got.

#8005 Update Bumblebee max KSP version to 1.10
  NetKAN/Bumblebee.netkan
Labels: Easy, Fix compatibility

#8006 Add TestLite
  NetKAN/TestLite.netkan
Labels: Blocked-on-Mod-Author, Easy, Mod-request, Pull request

#8007 Update TestLite compatibility
  NetKAN/TestLite.netkan
Labels: Fix compatibility

#8008 Fix Spectra install
  NetKAN/Spectra.netkan
Labels: Fix relationships

#8018 Fix MissionController2 install
  NetKAN/MissionController2.netkan
Labels: Blocked-on-Mod-Author, Fix install, Pull request

#8024 Split out Grannus ribbons
  NetKAN/Grannus-RibbonPack-FromGEP.netkan
  NetKAN/Grannus-RibbonPack-FromGPP.netkan
  NetKAN/GrannusExpansionPack.netkan
Labels: Fix install, Pull request

#8032 Freeze KrakenScience
  NetKAN/KrakenScience.frozen
Labels: Easy, Pull request

#8035 Remove StockishProjectOrion vref
  NetKAN/StockishProjectOrion.netkan
Labels: Fix compatibility, Fix install, Pull request

#8036 vref for SpaceXLegs
  NetKAN/SpaceXLegs.netkan
Labels: Fix compatibility

#8037 Add author to EarlyBird
  NetKAN/EarlyBird.netkan
Labels: Easy, Pull request

#7880 Add LunaMultiplayer
  NetKAN/LunaMultiplayer.netkan
Labels: Blocked-on-Mod-Author, In progress

#8046 Add SpaceTuxLibrary depends to KerbalConstructionTime
  NetKAN/KerbalConstructionTime.netkan
Labels: Fix relationships

#8050 Allow out of order releases for DockRotate
  NetKAN/DockRotate.netkan
Labels: Fix versioning, Pull request

#8061 Fix new Angel-125 installs
  NetKAN/DSEV.netkan
  NetKAN/Heisenberg.netkan
  NetKAN/MOLE.netkan
Labels: Fix install, Fix license, Fix relationships, Pull request

#8067 Scs
  NetKAN/SolarCycleSimulator.netkan
Labels: Waiting on PR creator
