Repository KSP-CKAN/NetKAN, pull requests merged in 2020-08, with the labels that each got.

#8081 New maintainer for OPTSpacePlaneMain
  NetKAN/OPTSpacePlaneMain.frozen
  NetKAN/OPTSpacePlaneMain.netkan
Labels: Mod-request, Pull request

#8086 Update OPT relationships
  NetKAN/OPTReconfig.netkan
  NetKAN/OPTSpacePlaneMain.netkan
  NetKAN/OPTSpacePlaneParts.netkan
Labels: Fix relationships

#8087 EVARefueling and LadderWarp support
  NetKAN/EVARefueling.netkan
  NetKAN/LadderWarp.netkan
Labels: Easy, Mod-request, Pull request

#8095 Fix GroundEffect install, compatibility
  NetKAN/GroundEffect.netkan
Labels: Fix compatibility, Fix install

#8097 New maintainer for EnvironmentalVisualEnhancements
  NetKAN/EnvironmentalVisualEnhancements.netkan
Labels: Pull request

#8104 Relationship updates for JadeOfMaar's mods
  NetKAN/AirlineKuisine.netkan
  NetKAN/RationalResources.netkan
Labels: Fix relationships

#8105 Set compatibility for Kopernicus Expansion Continued
  NetKAN/KopernicusExpansionContinued-CometTail.netkan
  NetKAN/KopernicusExpansionContinued-Common.netkan
  NetKAN/KopernicusExpansionContinued-EVAFootprints.netkan
  NetKAN/KopernicusExpansionContinued-EmissiveFX.netkan
  NetKAN/KopernicusExpansionContinued-ModularNoise.netkan
  NetKAN/KopernicusExpansionContinued-ProceduralGasGiants.netkan
  NetKAN/KopernicusExpansionContinued-ReentryEffects.netkan
  NetKAN/KopernicusExpansionContinued-RegionalPQSMods.netkan
  NetKAN/KopernicusExpansionContinued-VertexHeightDeformity.netkan
  NetKAN/KopernicusExpansionContinued-VertexHeightMap.netkan
  NetKAN/KopernicusExpansionContinued-Wormholes.netkan
Labels: Fix compatibility

#8116 Update SDHI-ServiceModuleSystem compatibility
  NetKAN/SDHI-ServiceModuleSystem.netkan
Labels: Fix compatibility

#8118 Add CRE
  NetKAN/CRE.netkan
Labels: Mod-request, Pull request

#8119 vref for SSTOProject
  NetKAN/SSTOProject.netkan
Labels: Fix compatibility

#8120 Update PreciseEditor.netkan
  NetKAN/PreciseEditor.netkan
Labels: Blocked-on-Mod-Author, Pull request
