Repository KSP-CKAN/NetKAN, pull requests merged in 2020-03, with the labels that each got.

#7748 Conflict with InfernalRobotics-LegacyParts
  NetKAN/InfernalRoboticsRealismOverhaul.netkan
Labels: Fix relationships

#7755 Update ScottManleyHeadPack repo
  NetKAN/ScottManleyHeadPack.netkan
Labels: Easy

#7765 Add RealExoplanets
  NetKAN/RealExoplanets.netkan
Labels: Mod-request, Pull request

#7756 Feature/micha maint
  NetKAN/ConnectedLivingSpace.netkan
  NetKAN/ShipManifest.netkan
Labels: Waiting on PR creator

#7793 Add Reentry Particle Effect Renewed from SpaceDock
  NetKAN/ReentryParticleEffect.netkan
Labels: Blocked-on-Other

#7797 Add recommendations for SimpleConstruction
  NetKAN/SimpleConstruction.netkan
Labels: Fix relationships

#7794 Force default sunflare for BeyondHome
  NetKAN/BeyondHome.netkan
  NetKAN/Scatterer-sunflare.netkan
Labels: Fix relationships, In progress, Pull request

#7800 Sunflare fix for GameslinxPlanetOverhaul
  NetKAN/GPO.netkan
Labels: Fix relationships, Pull request
