Repository KSP-CKAN/NetKAN, pull requests merged in 2020-12, with the labels that each got.

#8250 Add PartOverhaulIntegration
  NetKAN/PartOverhaulIntegration.netkan
Labels: Mod-request, Pull request

#8252 PhoenixIndustries no longer needs TextureReplacer
  NetKAN/PhoenixIndustries.netkan
Labels: Easy, Fix install, Fix relationships, Pull request

#8254 Don't install Buffalo's Ships folder as part of Pathfinder
  NetKAN/Pathfinder.netkan
Labels: Easy, Fix install, Pull request

#8257 Add MinmusSpaceCenter
  NetKAN/MinmusSpaceCenter.netkan
Labels: Easy, Mod-request, Pull request

#8258 Inflate with GitHub Action
  .github/workflows/inflate.yml
  .travis.yml
Labels: Easy, Pull request

#8259 Current B9-PWings depends on FAR
  NetKAN/B9-PWings-Fork.netkan
Labels: Easy, Fix relationships, Pull request

#8264 Update references to migrated repositories
  NetKAN/CryoTanks-Core.netkan
  NetKAN/CryoTanks.netkan
  NetKAN/DeployableEngines.netkan
  NetKAN/DynamicBatteryStorage.netkan
  NetKAN/Kronometer.netkan
  NetKAN/NearFutureProps.netkan
Labels: Easy, Pull request

#8265 Update NewTantaresLV compat to 1.11
  NetKAN/NewTantaresLV.netkan
Labels: Easy, Fix compatibility, Pull request

#8267 Turn off auto-epoching for DiRT
  NetKAN/DiRT.netkan
Labels: Easy, Fix versioning, Pull request

#8268 Freeze xScience
  NetKAN/xScience.frozen
Labels: Easy, Pull request

#8269 Update LessRealThanReal compatibility
  NetKAN/LessRealThanReal.netkan
Labels: Easy, Fix compatibility, Pull request

#8272 Allow DeepFreeze without BackgroundResources
  NetKAN/DeepFreeze.netkan
Labels: Fix relationships

#8273 Add KerbalInventoryForAll
  NetKAN/KerbalInventoryForAll.netkan
Labels: Easy, Mod-request, Pull request

#8274 Index Waterfall and WaterfallRestock
  NetKAN/Waterfall.netkan
  NetKAN/WaterfallRestock.netkan
Labels: Mod-request, Pull request

#8280 Update ModuleManager compatibility to 1.11
  NetKAN/ModuleManager.netkan
Labels: Easy, Fix compatibility, Pull request

#8281 Override compat of LMP 0.27.0 to KSP 1.11 and remove vref
  NetKAN/LunaMultiplayer.netkan
Labels: Fix compatibility, Pull request

#8282 Vref for BeamedPowerPlugin
  NetKAN/BeamedPowerPlugin-Realistic.netkan
  NetKAN/BeamedPowerPlugin.netkan
Labels: Easy, Fix compatibility, Pull request

#8289 Add TechTreeKompacted
  NetKAN/TechTreeKompacted.netkan
Labels: Mod-request, Pull request

#8262 Manually triggerable inflate Action
  .github/workflows/manual_inflate.yml
Labels: Discussion needed, Pull request

#8290 Vref for TestLite
  NetKAN/TestLite.netkan
Labels: Fix compatibility, Pull request

#8292 Remove KSPIE Incompatibilty
  NetKAN/KiwiTechTree.netkan
Labels: Fix relationships
