Repository KSP-CKAN/NetKAN, pull requests merged in 2020-01, with the labels that each got.

#7615 Set unknown or missing licenses
  NetKAN/AdvancedFlyByWire-Linux.netkan
  NetKAN/AdvancedFlyByWire-OSX.netkan
  NetKAN/AdvancedFlyByWire.netkan
  NetKAN/AoATechnologies.netkan
  NetKAN/BetterScienceLabsContinued.netkan
  NetKAN/CustomAsteroids-Pops-Stock-Inner.netkan
  NetKAN/CustomAsteroids-Pops-Stock-Outer.netkan
  NetKAN/CustomAsteroids-Pops-Stock-Stockalike.netkan
  NetKAN/CustomAsteroids.netkan
  NetKAN/DarkMultiPlayer.netkan
  NetKAN/EditorExtensionsRedux.netkan
  NetKAN/EmDriveByBeale.netkan
  NetKAN/EngineLightRelit.netkan
  NetKAN/GAP.netkan
  NetKAN/JanitorsCloset.netkan
  NetKAN/KASFrench.netkan
  NetKAN/Kerbalverse.netkan
  NetKAN/KramaxAutopilotContinued.netkan
  NetKAN/KustomKerbals.netkan
  NetKAN/MechJebForAll.netkan
  NetKAN/MinAmbLightUpd.netkan
  NetKAN/NavUtilitiesContinued.netkan
  NetKAN/OkramSA.netkan
  NetKAN/PartWizardContinued.netkan
  NetKAN/RSSeaDragon.netkan
  NetKAN/RealScaleBoosters.netkan
  NetKAN/RealScaleBoostersStockalike.netkan
  NetKAN/RevampedStockSystem.netkan
  NetKAN/SDHI-SharedAssets.netkan
  NetKAN/Syncrio.netkan
  NetKAN/TheGoldStandard.netkan
  NetKAN/Trajectories.netkan
  NetKAN/UtilityWeight.netkan
  NetKAN/VentralDrill.netkan
  NetKAN/WaterLaunchSites.netkan
Labels: Easy, Fix license, Pull request

#7637 Add Memorial Wall
  NetKAN/MemorialWall.netkan
Labels: Discussion needed

#7638 Fix ManeuverD version regex
  NetKAN/ManeuverD.netkan
Labels: Pull request

#7608 New RPM fork
  NetKAN/RasterPropMonitor-Core.netkan
  NetKAN/RasterPropMonitor.netkan
Labels: Blocked-on-Mod-Author

#7639 De-meta BeyondHome
  NetKAN/BeyondHome.netkan
Labels: Blocked-on-Other

#7655 Add Bulb Evolved from SpaceDock
  NetKAN/BulbEvolved.netkan
Labels: Blocked-on-Other
