Repository KSP-CKAN/NetKAN, pull requests merged in 2020-11, with the labels that each got.

#8205 Add MissingRobotics
  NetKAN/MissingRobotics.netkan
Labels: Easy, Mod-request, Pull request

#8207 Add Xingyun2
  NetKAN/Xingyun2.netkan
Labels: Easy, Mod-request, Pull request

#8208 Install mods' TextureReplacer assets into own subdirectories
  NetKAN/Astro-Cosmonauts.frozen
  NetKAN/AustrianSpaceAgency.frozen
  NetKAN/CustomDesignSpacesuits-Steampunk.frozen
  NetKAN/DFBetweentheStarsSkybox.netkan
  NetKAN/DFLargeMagellanicCloudSkybox.netkan
  NetKAN/DFNGC3115Skybox.netkan
  NetKAN/EpicSuits.frozen
  NetKAN/FwiffoRaredenSkybox.netkan
  NetKAN/GreenSkullRevived.netkan
  NetKAN/GregroxMultiColorSuitsPack.netkan
  NetKAN/GregroxsColoredEVAIVASuits.frozen
  NetKAN/HumanColoredFaces.frozen
  NetKAN/HumanStuff.netkan
  NetKAN/JupiteryJoolRecolor-TextureReplacer.frozen
  NetKAN/MilitarySuitTextures.frozen
  NetKAN/MilkyWay-Skybox.netkan
  NetKAN/Milkyway-Skybox-SpaceEngine.netkan
  NetKAN/NGC3371-Skybox.netkan
  NetKAN/OinkersSkybox.frozen
  NetKAN/OutOfGalaxySkybox.netkan
  NetKAN/PhoenixIndustries.netkan
  NetKAN/PhoenixIndustriesEVASuit.frozen
  NetKAN/PoliticalMap4kTexture.frozen
  NetKAN/PoliticalMap8kTexture.frozen
  NetKAN/PoliticalMapMilitaryTexture.frozen
  NetKAN/RN8474-8300-Skybox.netkan
  NetKAN/RedSpiderSkybox.netkan
  NetKAN/SN1006-Dark-Skybox.netkan
  NetKAN/SN1006-Light-Skybox.netkan
  NetKAN/SN1006-Unedited-Skybox.netkan
  NetKAN/ShuttleEVASuit.netkan
  NetKAN/SimpleFemaleKerbals.frozen
  NetKAN/StarTrekRebootUniformPack.frozen
  NetKAN/StarTrekTOSTunics.frozen
  NetKAN/SteampunkColorCodedSpaceSuits.frozen
  NetKAN/USIKolClassSuitsRedux.netkan
  NetKAN/WindowShineTR.netkan
  NetKAN/WinterKerbol.frozen
  NetKAN/halocharactercostumes.frozen
Labels: Fix install

#8219 Add Parallax-StockTextures and create texture dependency system
  NetKAN/Parallax-StockTextures.netkan
  NetKAN/Parallax.netkan
Labels: Fix relationships, Mod-request

#8220 Make BeyondHome provide Parallax-Textures
  NetKAN/BeyondHome.netkan
Labels: Fix relationships, Mod-enhancement

#8225 Update Kerbulator compatibility to 1.10
  NetKAN/Kerbulator.netkan
Labels: Fix compatibility

#8226 Add missing CKAN badged mods from SpaceDock
  NetKAN/AbovetheSkySoyuzTMAandR7.frozen
  NetKAN/AbovetheSkySoyuzTMAandR7.netkan
  NetKAN/AngaraRocketPack.frozen
  NetKAN/AngaraRocketPack.netkan
  NetKAN/HawkSpaceCenter.netkan
  NetKAN/Helvica.netkan
Labels: Mod-request, Needs looking into, Pull request

#8228 Kiwi Tech Tree
  NetKAN/KiwiTechTree.netkan
Labels: Mod-request, Pull request

#8235 RocketSoundenhancement
  NetKAN/RocketSoundEnhancement-Config-Default.netkan
  NetKAN/RocketSoundEnhancement.netkan
Labels: In progress, Mod-request, Pull request

#8239 Add KylandersFlagPack
  NetKAN/KylandersFlagPack.netkan
Labels: Easy, Mod-request, Pull request

#8242 Install craft files to Ships folder
  NetKAN/BDArmoryContinued.netkan
  NetKAN/Buffalo.netkan
  NetKAN/FlatBtmShtlSys.netkan
  NetKAN/FuelTanksPlus.netkan
  NetKAN/MS-SRBs.netkan
  NetKAN/ModularRocketSystem.netkan
  NetKAN/RetroFuture.netkan
Labels: Easy, Fix install, Pull request

#8243 More craft file install fixes
  NetKAN/AircraftCarrierAccessories.netkan
  NetKAN/DunaDirect.netkan
Labels: Easy, Fix install, Pull request
