Repository KSP-CKAN/NetKAN, pull requests merged in 2020-06, with the labels that each got.

#7951 Add GroundEffect
  NetKAN/GroundEffect.netkan
Labels: Mod-request, Pull request

#7959 Add RealFuels-Stock to CKAN
  NetKAN/RealFuels-Stock.netkan
Labels: Mod-request, Pull request

#7965 Add EnduranceReconfig missing depends
  NetKAN/EnduranceReconfig.netkan
Labels: Fix relationships

#7966 Unfreeze netkans frozen in error
  NetKAN/AirParkContinued.frozen
  NetKAN/AirParkContinued.netkan
  NetKAN/BDDMP.frozen
  NetKAN/BDDMP.netkan
  NetKAN/CactEyeCommunity.frozen
  NetKAN/CactEyeCommunity.netkan
  NetKAN/CloakingDevice.frozen
  NetKAN/CloakingDevice.netkan
  NetKAN/ETT.netkan
  NetKAN/EngineLighting.frozen
  NetKAN/EngineLighting.netkan
  NetKAN/EveryS.frozen
  NetKAN/EveryS.netkan
  NetKAN/HullBreach.frozen
  NetKAN/HullBreach.netkan
  NetKAN/KHWearableKISProps.netkan
  NetKAN/LightsOut.frozen
  NetKAN/LightsOut.netkan
  NetKAN/NorthKerbinDynamics.frozen
  NetKAN/NorthKerbinDynamics.netkan
  NetKAN/PrakasaAeroworks.frozen
  NetKAN/PrakasaAeroworks.netkan
  NetKAN/SerialIO.frozen
  NetKAN/SerialIO.netkan
  NetKAN/ShowAllFuelsContinued.frozen
  NetKAN/ShowAllFuelsContinued.netkan
  NetKAN/SolarisHypernautics.frozen
  NetKAN/SolarisHypernautics.netkan
Labels: Easy, Pull request

#7969 Filter duplicate folders
  NetKAN/BluedogDB.netkan
  NetKAN/DiRT.netkan
  NetKAN/SpearofLonginus.netkan
  NetKAN/StockPlugins.netkan
Labels: Easy, Fix install, Pull request

#7970 Fix KWS install
  NetKAN/KWSKerbalWeaponsSystem.netkan
Labels: Fix install

#7972 New fork for PersistentThrust
  NetKAN/PersistentThrust.netkan
Labels: Blocked-on-Mod-Author, Mod-request, Pull request

#7975 Tag untagged modules
  NetKAN/AGExt.netkan
  NetKAN/AllYAll.netkan
  NetKAN/B9HXReconfig.netkan
  NetKAN/BetterTimeWarpCont.netkan
  NetKAN/KerbalTubes.netkan
  NetKAN/SOS.netkan
  NetKAN/TweakScaleCompanion-ReStockPlus.netkan
  NetKAN/WalkAbout.netkan
Labels: Easy, Pull request

#7981 Tags for NodeSplitter
  NetKAN/NodeSplitter.netkan
Labels: Easy, Pull request

#7982 Wild Blue Industries
  NetKAN/BARIS.netkan
  NetKAN/BarisBridge.netkan
  NetKAN/Buffalo.frozen
  NetKAN/Buffalo.netkan
  NetKAN/ClassicStockResources.netkan
  NetKAN/KerbalActuators.netkan
  NetKAN/Pathfinder.frozen
  NetKAN/Pathfinder.netkan
  NetKAN/WildBlueTools.frozen
  NetKAN/WildBlueTools.netkan
Labels: Mod-request, Pull request

#7988 Add Knes
  NetKAN/Knes.netkan
Labels: Mod-request, Pull request

#7990 Back to download property for mods that don't need http kref
  NetKAN/AdaptiveDockingNode.frozen
  NetKAN/DDSLoader.netkan
  NetKAN/KerbalStats.netkan
  NetKAN/Kethane.netkan
  NetKAN/ModularFuelTanks.netkan
  NetKAN/SpaceShuttleEngines.netkan
  NetKAN/SurveyTransponder.netkan
  NetKAN/TalisarParts.netkan
Labels: Easy, Pull request

#7994 Fix RecycledParts craft installs
  NetKAN/RecycledPartsAtomicAge.netkan
  NetKAN/RecycledPartsFarscape.netkan
  NetKAN/RecycledPartsRSCapsuledyne.netkan
Labels: Fix install

#7999 Update SSTOProject relationships
  NetKAN/SSTOProject.netkan
Labels: Easy, Fix relationships, Pull request
