Repository KSP-CKAN/NetKAN, pull requests merged in 2021-01, with the labels that each got.

#8294 GroundEffect is compatible with 1.11
  NetKAN/GroundEffect.netkan
Labels: Fix compatibility

#8300 Add Cressida
  NetKAN/Cressida.netkan
Labels: Mod-request, Pull request

#8302 Add ContractConfigurator-PlanesWithPurposes
  NetKAN/ContractConfigurator-PlanesWithPurposes.netkan
Labels: Mod-request, Pull request

#8306 Add SpaceXSuits
  NetKAN/SpaceXSuits.netkan
Labels: Mod-request, Pull request

#8275 Split out WBI play modes
  NetKAN/Buffalo-PlayMode-CRP.netkan
  NetKAN/Buffalo-PlayMode-ClassicStock.netkan
  NetKAN/Buffalo.netkan
  NetKAN/ClassicStockResources.netkan
  NetKAN/DSEV-PlayMode-CRP.netkan
  NetKAN/DSEV-PlayMode-ClassicStock.netkan
  NetKAN/DSEV-PlayMode-Pristine.netkan
  NetKAN/DSEV.netkan
  NetKAN/Heisenberg-PlayMode-CRP.netkan
  NetKAN/Heisenberg-PlayMode-ClassicStock.netkan
  NetKAN/Heisenberg-PlayMode-Pristine.netkan
  NetKAN/Heisenberg-PlayMode-Simplified.netkan
  NetKAN/Heisenberg.netkan
  NetKAN/HooliganLabsAirships.netkan
  NetKAN/MOLE-PlayMode-CRP.netkan
  NetKAN/MOLE-PlayMode-ClassicStock.netkan
  NetKAN/MOLE-PlayMode-Pristine.netkan
  NetKAN/MOLE.netkan
  NetKAN/Pathfinder-PlayMode-CRP.netkan
  NetKAN/Pathfinder-PlayMode-ClassicStock.netkan
  NetKAN/Pathfinder-PlayMode-Pristine.netkan
  NetKAN/Pathfinder-PlayMode-Simplified.netkan
  NetKAN/Pathfinder.netkan
  NetKAN/WildBlue-PlayMode-CRP.netkan
  NetKAN/WildBlue-PlayMode-ClassicStock.netkan
  NetKAN/WildBlue-PlayMode-Pristine.netkan
  NetKAN/WildBlue-PlayMode-Simplified.netkan
  NetKAN/WildBlue-PlayMode-USI.netkan
  NetKAN/WildBlueTools.netkan
Labels: Bug, Fix install, Fix relationships, In progress, Mod-request, Pull request

#8307 Update MechJeb2 compatibility
  NetKAN/MechJeb2.netkan
Labels: Easy, Fix compatibility, Pull request

#8308 Add KerbinSideRemastered to KSCExtended's dependencies
  NetKAN/KSCExtended.netkan
Labels: Easy, Fix relationships, Pull request

#8312 Fix PlanesWithPurposes install stanza
  NetKAN/ContractConfigurator-PlanesWithPurposes.netkan
Labels: Fix install, Pull request

#8309 Minimum compatible version overrides for Snark's mods
  NetKAN/AntennaSleep.netkan
  NetKAN/AttitudeAdjuster.netkan
  NetKAN/AutoAGL.netkan
  NetKAN/BetterBurnTime.netkan
  NetKAN/BetterCrewAssignment.netkan
  NetKAN/DefaultActionGroups.netkan
  NetKAN/IndicatorLights.netkan
  NetKAN/IndicatorLightsCommunityExtensions.netkan
  NetKAN/MissingHistory.netkan
  NetKAN/SimpleFuelSwitch.netkan
  NetKAN/Snarkiverse.netkan
  NetKAN/VABReorienter.netkan
  NetKAN/VariantPersist.netkan
  NetKAN/VectorRepurposed.netkan
Labels: Blocked-on-CKAN-Feature, Fix compatibility, In progress, Pull request

#8313 Move KIS back to Extraplanetary Launchpads's recommends list
  NetKAN/ExtraPlanetaryLaunchpads.netkan
Labels: Easy, Fix relationships, Pull request

#8314 Extend current Scatterer compatibility back to KSP 1.9
  NetKAN/Scatterer-config.netkan
  NetKAN/Scatterer-sunflare.netkan
  NetKAN/Scatterer.netkan
Labels: Easy, Fix compatibility, Pull request

#8316 Override min game version for WarpEverywhere
  NetKAN/WarpEverywhere.netkan
Labels: Easy, Fix compatibility, Pull request

#8318 Freeze mods deleted from SpaceDock
  NetKAN/KSRe.frozen
  NetKAN/OpenTree.frozen
Labels: Easy

#8320 Add DreskillerBase
  NetKAN/DreskillerBase.netkan
Labels: Blocked-on-Mod-Author, Mod-request, Pull request

#8322 Add mods from SpaceDock
  NetKAN/BuranEnergia.netkan
  NetKAN/KSPRescueContractFix.netkan
  NetKAN/PitchPerfect.netkan
Labels: Mod-request, Pull request

#8323 Freeze mods with long term indexing errors
  NetKAN/AllTweak.frozen
  NetKAN/CareerModePartCostNullifer.frozen
  NetKAN/ContractConfigurator-KerbalAcademy.frozen
  NetKAN/SuperBattery.frozen
  NetKAN/TheVerse.frozen
  NetKAN/WoodSpaceProgram.frozen
  NetKAN/kOSPropMonitor.frozen
Labels: Easy, Pull request

#8326 New override for a Snark mod
  NetKAN/BetterCrewAssignment.netkan
Labels: Easy, Fix compatibility, Pull request

#8330 Add GrannusExpansionPack-Rescale
  NetKAN/GrannusExpansionPack-Rescale.netkan
  NetKAN/GrannusExpansionPack.netkan
Labels: Easy, Fix relationships, Mod-request, Pull request

#8332 Cache permissions workaround
  .github/workflows/inflate.yml
Labels: Bug, Pull request

#7964 Add kRPC-MechJeb
  NetKAN/kRPC-MechJeb.netkan
Labels: Blocked-on-Mod-Author, Mod-request, Pull request

#8334 Make SpaceLink compatible with its full game version ramge
  NetKAN/SpaceLink.netkan
Labels: Easy, Fix compatibility

#8336 Add VultureSystem
  NetKAN/VultureSystem.netkan
Labels: Easy, Mod-request, Pull request

#8337 Fix CommunityPartsTitles install
  NetKAN/CommunityPartsTitles.netkan
  NetKAN/CommunityPartsTitlesExtrasCategory.netkan
  NetKAN/CommunityPartsTitlesExtrasNoCCKDup.netkan
Labels: Easy, Fix install, Pull request

#8339 Allow out of order releases for Kopernicus
  NetKAN/Kopernicus.netkan
Labels: Fix versioning, Pull request

#8340 Min version overrides for SpaceDock mods
  NetKAN/JX2Antenna.netkan
  NetKAN/ManhattanAirport.netkan
  NetKAN/ModularLaunchPads.netkan
  NetKAN/SteeringTweaker.netkan
Labels: Easy, Fix compatibility, Pull request

#8341 Select the right asset
  NetKAN/AdvancedFlyByWire-Linux.netkan
  NetKAN/AdvancedFlyByWire-OSX.netkan
  NetKAN/AirlockPlus.netkan
  NetKAN/DockingCamKURS.netkan
  NetKAN/PicoPort4AllSizes.netkan
Labels: Bug, Easy, Pull request

#8342 Add mods from SpaceDock
  NetKAN/BetterEarlyTree.netkan
  NetKAN/EnvironmentalVisualEnhancements.netkan
Labels: Mod-request, Pull request
