Repository KSP-CKAN/NetKAN, pull requests merged in 2021-06, with the labels that each got.

#8555 Freeze FruitGoose's mods
  NetKAN/APPLE.frozen
  NetKAN/FIG.frozen
  NetKAN/GRAPES.frozen
  NetKAN/LIME.frozen
  NetKAN/MANGO.frozen
  NetKAN/ORANGE.frozen
  NetKAN/PEAR.frozen
  NetKAN/PLUM.frozen
  NetKAN/PRUNES.frozen
  NetKAN/VertikalSpeedIndicator.frozen
Labels: Easy, Freeze

#8560 Add missing RealisticPowerDraw depends
  NetKAN/RealisticPowerDraw.netkan
Labels: Easy, Fix relationships, Pull request

#8566 Convert PlanningNode netkan to YAML
  .gitattributes
  NetKAN/PlanningNode.netkan
Labels: Easy, Pull request

#8565 Hard code IFS repo links
  NetKAN/InterstellarFuelSwitch-Core.netkan
  NetKAN/InterstellarFuelSwitch.netkan
Labels: Easy, Pull request

#8567 Hard code DMTanks repo links
  NetKAN/DMTanks-AeroRTG.netkan
  NetKAN/DMTanks-CargoBays.netkan
  NetKAN/DMTanks-Fuselage.netkan
  NetKAN/DMTanks-SphericalTanks.netkan
Labels: Easy, Pull request

#8569 Fix AutoHibernate install
  NetKAN/AutoHibernate.netkan
Labels: Easy, Fix install, Pull request

#8575 Freeze BuranEnergia
  NetKAN/BuranEnergia.frozen
Labels: Easy, Fix license, Pull request

#8576 StockWaterfallEffects no longer conflicts with ReStock
  NetKAN/StockWaterfallEffects.netkan
Labels: Easy, Fix relationships, Pull request

#8579 Fix PlanetShine indentation
  NetKAN/PlanetShine.netkan
Labels: Easy, Pull request

#8580 Update TheWorldBeyond license
  NetKAN/TheWorldBeyond.frozen
Labels: Easy, Fix license, Pull request

#8581 Remove EVE-Config provides from StrangeNewWorlds
  NetKAN/AstronomersVisualPack.netkan
  NetKAN/EnvironmentalVisualEnhancements-LR.frozen
  NetKAN/SciFiVisualEnhancements-WeimaranersTweaks.netkan
  NetKAN/SciFiVisualEnhancements.netkan
  NetKAN/Spectra.netkan
  NetKAN/StockVisualEnhancements.netkan
  NetKAN/StrangeNewWorlds.netkan
Labels: Fix relationships, Pull request

#8591 Add Harmony2 dependency to LMP, update compatibility
  NetKAN/LunaMultiplayer.netkan
Labels: Fix compatibility, Fix relationships, Pull request

#8599 Fix TweakScale install stanzas
  NetKAN/TweakScale.netkan
Labels: Fix install, Pull request

#8601 Revert "Fix TweakScale install stanzas (#8599)"
  NetKAN/TweakScale.netkan
Labels: Fix install

#8604 Remove vref from Kerbalism-Config-RO
  NetKAN/Kerbalism-Config-RO.netkan
Labels: Fix compatibility, Pull request

#8606 Add TantaresSAF
  NetKAN/TantaresSAF.netkan
Labels: Mod-request, Pull request

#8607 Freeze FwiffoRaredenSkybox
  NetKAN/FwiffoRaredenSkybox.frozen
Labels: Freeze, Pull request

#8595 Unfreeze RSSVE
  NetKAN/RSSVE-HR.frozen
  NetKAN/RSSVE-HR.netkan
  NetKAN/RSSVE-LR.frozen
  NetKAN/RSSVE-LR.netkan
Labels: Mod-request, Pull request

#8608 Fix RSSVE dependency on DistantObject
  NetKAN/RSSVE-HR.netkan
  NetKAN/RSSVE-LR.netkan
Labels: Easy, Fix relationships, Pull request

#8609 Pin Helvica min compat
  NetKAN/Helvica.netkan
Labels: Easy, Fix compatibility

#8610 Fixes missing DLL file issue
  NetKAN/InterstellarRedistributable.netkan
  NetKAN/KSPInterstellarExtended.netkan
  NetKAN/PhotonSailor.netkan
Labels: Fix install, Pull request
