Repository KSP-CKAN/NetKAN, pull requests merged in 2021-07, with the labels that each got.

#8614 Mark DerivativeTextures compatible with any version
  NetKAN/DerivativeTextures.netkan
Labels: Fix compatibility

#8617 Freeze TerrasIgnotas
  NetKAN/TerrasIgnotas.frozen
Labels: Freeze

#8621 Update ModuleManager compatibility to 1.12
  NetKAN/ModuleManager.netkan
Labels: Fix compatibility, Pull request

#8623 New B9PW fork
  NetKAN/B9-PWings-Fork.netkan
Labels: Blocked-on-Mod-Author, In progress, Pull request

#8625 Update KSCExtended relationships after adoption
  NetKAN/KSCExtended.netkan
Labels: Fix relationships, Pull request

#8628 Compat and dep updates for ModularLaunchPads
  NetKAN/ModularLaunchPads.netkan
Labels: Fix compatibility, Fix relationships, Pull request

#8629 Update Parallax compatibility for new release
  NetKAN/Parallax.netkan
Labels: Fix compatibility, Pull request

#8631 Change Parallax min KSP version to 1.11
  NetKAN/Parallax.netkan
Labels: Fix compatibility, Pull request

#8638 Fix KerbinSideRemasteredTLA install location
  NetKAN/KerbinSideRemasteredTLA.netkan
Labels: Fix install, Pull request

#8640 hard code minimum KSP version Interstellar Redistributable
  NetKAN/InterstellarRedistributable.netkan
Labels: Fix compatibility

#8641 Freeze unmaintained metanetkans with hardcoded downloads
  NetKAN/SASS-DRP.frozen
  NetKAN/SASS-ER.frozen
  NetKAN/SASS-NH.frozen
  NetKAN/SASS-OPM.frozen
  NetKAN/SASS-RevJ.frozen
  NetKAN/SASS-RevSS.frozen
  NetKAN/SASS-SE.frozen
  NetKAN/SASS-Saru.frozen
  NetKAN/SASS-StockalikeNeptune.frozen
  NetKAN/SASS-UL.frozen
Labels: Easy, Freeze, Pull request

#8642 De-meta RadioFreeKerbin metanetkan with hardcoded download
  NetKAN/RadioFreeKerbin.netkan
Labels: Pull request

#8643 Vref for RadioFreeKerbin
  NetKAN/RadioFreeKerbin.netkan
Labels: Easy, Fix compatibility, Pull request

#8644 De-meta GPP mods
  NetKAN/GPP.netkan
  NetKAN/GPPCloudsHighRes.netkan
  NetKAN/GPPCloudsLowRes.netkan
  NetKAN/GPPSecondary.netkan
  NetKAN/GPPTextures.netkan
Labels: Fix compatibility, Pull request

#8645 Move 'Grannus' filter to correct install stanza
  NetKAN/GPP.netkan
Labels: Fix install, Pull request

#8652 Freeze KerbalSpaceRebalanced
  NetKAN/KerbalSpaceRebalanced.frozen
Labels: Easy, Freeze

#8646 Strip date portion of SIMPLEX* and TETRIXTechTree versions
  NetKAN/SIMPLEXKerbalism.netkan
  NetKAN/SimplexPropulsion.netkan
  NetKAN/SimplexTechTree.netkan
  NetKAN/TETRIXTechTree.netkan
Labels: Fix versioning, Pull request

#8655 Freeze two of Nertea's mods
  NetKAN/KerbalAtomics-NFECompatibility.frozen
  NetKAN/StationPartsExpansionRedux-Metal.frozen
Labels: Easy, Freeze

#8658 Freeze CARP again
  NetKAN/CommunityAgenciesRevivalProject.frozen
Labels: Freeze

#8663 Fix StarshipLaunchExpansion relationships
  NetKAN/StarshipLaunchExpansion.netkan
Labels: Easy, Fix relationships

#8674 Unfreeze mods adopted by zer0Kerbal
  NetKAN/Biomatic.frozen
  NetKAN/Biomatic.netkan
  NetKAN/BiomaticForAll.frozen
  NetKAN/BiomaticForAll.netkan
  NetKAN/TheGoldStandard.frozen
  NetKAN/TheGoldStandard.netkan
Labels: Mod-request, Pull request

#8677 Fix xScienceContinued dependencies
  NetKAN/xScienceContinued.netkan
Labels: Easy, Fix relationships, Pull request

#8679 Move BiomaticForAll from Biomatic recommends to suggests
  NetKAN/Biomatic.netkan
Labels: Fix relationships, Pull request

#8681 Clean up SimpleOrbitCalculator
  NetKAN/SimpleOrbitCalculator.netkan
Labels: Fix install, Fix relationships, Pull request

#8667 add CanaveralPads
  NetKAN/CanaveralPads.netkan
  NetKAN/RSS-CanaveralHD.netkan
Labels: Mod-request, Pull request
