Repository KSP-CKAN/NetKAN, pull requests merged in 2021-11, with the labels that each got.

#8838 Add DARTRange
  NetKAN/DARTRange.netkan
Labels: Mod-request, Pull request

#8839 DARTRange authors
  NetKAN/DARTRange.netkan
Labels: Easy, Pull request

#8842 Pin PhoenixIndustries min compat
  NetKAN/PhoenixIndustries.netkan
Labels: Pull request, Fix compatibility

#8844 Add resources.manual for ModuleManager
  NetKAN/ModuleManager.netkan
Labels: Easy, Pull request

#8846 Freeze MidweeksLesserRedTUFXConfig
  NetKAN/MidweeksLesserRedTUFXConfig.frozen
Labels: Pull request, Freeze

#8850 Fix EnvironmentalVisualEnhancements install
  NetKAN/EnvironmentalVisualEnhancements.netkan
Labels: Easy, Fix install, Pull request

#8851 Fix install stanza for Adiri's TUFX Profiles
  NetKAN/C1ustasTUFXProfiles.netkan
Labels: Easy, Fix install, Pull request

#8853 Fix GrondsMicrometeoriteShield install
  NetKAN/GrondsMicrometeoriteShield.netkan
Labels: Fix install, Pull request

#8854 MM dep for GrondsMicrometeoriteShield
  NetKAN/GrondsMicrometeoriteShield.netkan
Labels: Fix relationships, Pull request

#8857 More Scatterer compat adjustments
  NetKAN/Scatterer-config.netkan
  NetKAN/Scatterer-sunflare.netkan
  NetKAN/Scatterer.netkan
Labels: Pull request, Fix compatibility

#8860 Conflicts between MinorPlanetsExpansionRevived and MinorPlanetsExpansion
  NetKAN/MinorPlanetsExpansionRevived.netkan
Labels: Fix relationships, Pull request

#8862 Fix install_to capitalization of Scatterer config and sunflare
  NetKAN/Scatterer-config.netkan
  NetKAN/Scatterer-sunflare.netkan
  NetKAN/Scatterer.netkan
Labels: Fix install, Pull request

#8869 Switch ShipManifest back to PapaJoesSoup repo
  NetKAN/ShipManifest.netkan
Labels: Pull request, Waiting for new mod release

#8877 Try to rename ShipManifest's CLSInterfaces.dll
  NetKAN/ShipManifest.netkan
Labels: Blocked-on-Mod-Author, Fix install, Pull request, Bug

#8880 Try to enforce Scatterer compatibility for GPP and GEP
  NetKAN/GPP.netkan
  NetKAN/GPPSecondary.netkan
  NetKAN/GrannusExpansionPack.netkan
Labels: Pull request, Fix compatibility

#8881 GPP/GEP: version_min → min_version
  NetKAN/GPP.netkan
  NetKAN/GPPSecondary.netkan
  NetKAN/GrannusExpansionPack.netkan
Labels: Fix relationships, Pull request, Bug

#8882 Revert ShipManifest CLSInterfaces file rename
  NetKAN/ShipManifest.netkan
Labels: Easy, Fix install, Pull request

#8885 Add conflicts between ContractConfigurator-HistoricMissions variants
  NetKAN/ContractConfigurator-HistoricMissions.frozen
  NetKAN/ContractConfigurator-HistoricMissionsRSS.frozen
Labels: Fix relationships, Easy, Pull request

#8887 Tags, vref, and license fix for BrickMod
  NetKAN/BrickMod.netkan
Labels: Fix license, Pull request, Fix compatibility
