Repository KSP-CKAN/NetKAN, pull requests merged in 2021-03, with the labels that each got.

#8379 Switch KerbalChangelog to new fork
  NetKAN/KerbalChangelog.netkan
Labels: Easy, Pull request, Waiting on PR creator

#8387 Update CRE compatibility
  NetKAN/CRE.netkan
Labels: Easy, Fix compatibility

#8388 Homepage for CRE
  NetKAN/CRE.netkan
Labels: Easy, Pull request

#8394 CommunityPartsTitlesExtrasNoCCKDup update
  NetKAN/CommunityPartsTitlesExtrasNoCCKDup.netkan
Labels: Fix install, In progress, Pull request, Waiting on PR creator

#8395 Fix CommunityPartTitles installs
  NetKAN/CommunityPartsTitles.netkan
  NetKAN/CommunityPartsTitlesExtrasCategory.netkan
Labels: Easy, Fix install, Pull request

#8343 Add KSPW00tNow
  NetKAN/KSPW00tNow.netkan
Labels: Blocked-on-CKAN-Feature, Mod-request, Pull request

#8396 MM dep for OPTSpacePlaneMain
  NetKAN/OPTSpacePlaneMain.netkan
Labels: Fix relationships, Pull request

#8401 Make Kerbalism-Config-RO conflict with life support mods
  NetKAN/Kerbalism-Config-RO.netkan
Labels: Easy, Fix relationships, Pull request

#8402 Fix Tantares mods
  NetKAN/NewTantares.netkan
  NetKAN/NewTantaresLV.netkan
  NetKAN/Tantares.frozen
  NetKAN/TantaresLV.frozen
  NetKAN/TantaresSP.netkan
Labels: Fix compatibility, Fix install, Fix license, Pull request

#8405 Pin min compat of SciFiVisualEnhancements-WeimaranersTweaks
  NetKAN/SciFiVisualEnhancements-WeimaranersTweaks.netkan
Labels: Fix compatibility

#8406 Pin min compat of OuterKerbin
  NetKAN/OuterKerbin.netkan
Labels: Fix compatibility, Pull request

#8408 Pin Heracleitus min compat
  NetKAN/Heracleitus.netkan
Labels: Easy, Fix compatibility, Pull request

#8409 Freeze KSPW00tNow until Harmony2 is safe
  NetKAN/KSPW00tNow.frozen
Labels: Fix relationships, Pull request

#8410 Create ProvenanceAerospace.netkan
  NetKAN/ProvenanceAerospace.netkan
Labels: Mod-request, Pull request

#8411 Pin min compat of CARP and DMP
  NetKAN/CommunityAgenciesRevivalProject.netkan
  NetKAN/DarkMultiPlayer.netkan
Labels: Easy, Fix compatibility, Pull request

#8288 Add the Harmony lib as a package
  NetKAN/AirlockPlus.netkan
  NetKAN/Harmony2.netkan
  NetKAN/KSPW00tNow.frozen
  NetKAN/KSPW00tNow.netkan
  NetKAN/Kerbalism.netkan
  NetKAN/LunaMultiplayer.netkan
  NetKAN/TiltEm.netkan
Labels: Discussion needed, Mod-request, Pull request

#8412 Update Kerbalism's Harmony relationships
  NetKAN/Kerbalism.netkan
Labels: Fix relationships, Pull request

#8413 Add vrefs for Tantares SP and Tantares LV
  NetKAN/NewTantaresLV.netkan
  NetKAN/TantaresSP.netkan
Labels: Easy, Fix compatibility, Pull request

#8414 Mark ManeuverD as bundling Harmony1
  NetKAN/ManeuverD.netkan
Labels: Easy, Fix relationships

#8416 Pin min compat of ModularLaunchPads
  NetKAN/ModularLaunchPads.netkan
Labels: Easy, Fix compatibility, Pull request

#8417 Pin AATI-Flags min compat
  NetKAN/AATI-Flags.netkan
Labels: Easy, Fix compatibility, Pull request

#8419 Add KSPBurst
  NetKAN/KSPBurst-Lite.netkan
  NetKAN/KSPBurst.netkan
Labels: Mod-request, Pull request

#8426 MM dep for CustomAsteroids-Pops-OPM-Outer
  NetKAN/CustomAsteroids-Pops-OPM-Outer.netkan
Labels: Easy, Fix relationships, Pull request

#8428 Remove TestFlight's asset_match
  NetKAN/TestFlight.netkan
Labels: Easy, Pull request

#8429 Add vrefs to mods with unused version files
  NetKAN/BarisBridge.netkan
  NetKAN/CST100Starliner.netkan
  NetKAN/FelineUtilityRovers.netkan
  NetKAN/HullBreach.netkan
  NetKAN/JackOLantern.netkan
  NetKAN/LunaMultiplayer.netkan
  NetKAN/ManhattanAirport.netkan
  NetKAN/NoCrewRequirementContinued.netkan
  NetKAN/OldPartsRedux.netkan
  NetKAN/RFStockalike.netkan
  NetKAN/ShowAllFuelsContinued.netkan
  NetKAN/StreamlineEnginesRCSsandfueltanks.netkan
  NetKAN/UnKerballedStart.netkan
Labels: Easy, Fix compatibility, Pull request

#8430 Add new plugin : KspBugReport
  NetKAN/KSPBugReport.netkan
Labels: Mod-request, Pull request

#8434 Update BluedogDB relationships
  NetKAN/BluedogDB.netkan
Labels: Fix relationships, Pull request

#8435 Pin KSPArtemisSuit min compat
  NetKAN/KSPArtemisSuit.netkan
Labels: Easy, Fix compatibility

#8439 Pin min compat of Jatwaa's mods
  NetKAN/MOISTUnderwaterTechnologies.netkan
  NetKAN/PlanetaryStationCores.netkan
  NetKAN/PureElectricEngines.netkan
  NetKAN/SinkEmAll.netkan
Labels: Easy, Fix compatibility, Pull request

#8441 Add MM dep for mods with MM syntax
  NetKAN/CapsuleCorpKerbalKolonizationProgram.netkan
  NetKAN/JamesWebbForKerbal.netkan
  NetKAN/LosslessISRU.netkan
Labels: Easy, Fix relationships, Pull request

#8442 Pin min compat of NorthKerbinDynamicRenewed
  NetKAN/NorthKerbinDynamicRenewed.netkan
Labels: Easy, Fix compatibility, Pull request

#8445 Pin min compat of LOL221's mods
  NetKAN/OutOfGalaxySkybox.netkan
  NetKAN/RN8474-8300-Skybox.netkan
Labels: Easy, Fix compatibility, Pull request
