Repository KSP-CKAN/NetKAN, pull requests merged in 2021-12, with the labels that each got.

#8888 Fix AtomicTechIncJunkyards install
  NetKAN/AtomicTechIncJunkyards.netkan
Labels: Fix install, Pull request

#8898 Freeze Cashedowt's mods
  NetKAN/CashedowtEarthTUFXProfile.frozen
  NetKAN/RVE64KContinued.frozen
Labels: Easy, Pull request, Freeze

#8906 Add Breaking Ground mini mods
  NetKAN/MoreServos.netkan
  NetKAN/SLOTH.netkan
  NetKAN/ServoController.netkan
Labels: Mod-request, Pull request

#8908 Fix KerbalMiniShuttle install
  NetKAN/KerbalMiniShuttle.netkan
Labels: Easy, Fix install, Pull request

#8895 Taerobee
  NetKAN/Taerobee.frozen
  NetKAN/Taerobee.netkan
Labels: Pull request, Waiting for new mod release

#8910 Add B9PartSwitch dependency to StockWaterfallEffects
  NetKAN/StockWaterfallEffects.netkan
Labels: Fix relationships, Easy, Pull request

#8911 Add StratPlusPlus
  NetKAN/StratPlusPlus.netkan
Labels: Mod-request, Pull request

#8916 Update AtomicTechIncJunkyards license
  NetKAN/AtomicTechIncJunkyards.netkan
Labels: Fix license, Easy, Pull request

#8924 CactEye fixes
  NetKAN/CactEyeCommunityRefocused.netkan
Labels: Easy, Pull request

#8926 MM dep for ASSET-Mk1
  NetKAN/ASSET-Mk1.netkan
Labels: Fix relationships, Easy, Pull request

#8927 Unfreeze frozen NESD mod
  NetKAN/StreamlineEnginesRCSsandfueltanks.frozen
  NetKAN/StreamlineEnginesRCSsandfueltanks.netkan
Labels: Easy, Pull request, Freeze

#8929 Update FacilityTree.netkan
  NetKAN/FacilityTree.netkan
Labels: Fix relationships, Pull request

#8933 Update Snark compat overrides
  NetKAN/DefaultActionGroups.netkan
  NetKAN/IndicatorLights.netkan
  NetKAN/MissingHistory.netkan
Labels: Easy, Pull request, Fix compatibility
