Repository KSP-CKAN/NetKAN, pull requests merged in 2021-04, with the labels that each got.

#8448 Add Benjee10Suits
  NetKAN/Benjee10Suits.netkan
Labels: Mod-request, Pull request

#8454 Override max compat for ProceduralFairings-ForEverything
  NetKAN/ProceduralFairings-ForEverything.netkan
Labels: Easy, Fix compatibility, Pull request

#8455 MM dep for MANGO
  NetKAN/MANGO.netkan
Labels: Easy, Fix relationships, Pull request

#8456 Add PRUNES
  NetKAN/PRUNES.netkan
Labels: Mod-request, Pull request

#8457 Adding KSP-Recall as a dependency, as requested by DasSkellet on forum.
  NetKAN/TweakScale.netkan
Labels: Fix relationships, Pull request

#8458 Pin min compat of SpaceXSuits
  NetKAN/SpaceXSuits.netkan
Labels: Easy, Fix compatibility, Pull request

#8461 Update FishyAntiMissileSpam install
  NetKAN/FishyAntiMissileSpam.netkan
Labels: Easy, Fix install, Pull request

#8463 Pin min compat of OldPartsRedux
  NetKAN/OldPartsRedux.netkan
Labels: Easy, Fix compatibility, Pull request

#8464 Vref for OldPartsRedux
  NetKAN/OldPartsRedux.netkan
Labels: Easy, Fix compatibility, Pull request

#8465 Update KerbinPlacePack deps
  NetKAN/KerbinPlacePack.netkan
Labels: Easy, Fix relationships, Pull request

#8467 Update kref for KerbinPlacePack
  NetKAN/KerbinPlacePack.netkan
Labels: Easy, Pull request

#8468 Update install for KerbinPlacePack
  NetKAN/KerbinPlacePack.netkan
Labels: Easy, Fix install, Pull request

#8469 Pin min compat of JPL-RSS
  NetKAN/JPL-RSS.netkan
Labels: Easy, Fix compatibility

#8470 MM dep for KerbinPlacePack
  NetKAN/KerbinPlacePack.netkan
Labels: Fix relationships

#8472 Delete ancient Perl scripts
  bin/firespitter-downloader
  bin/netkan-all
  bin/netkan-all.lean
Labels: Easy, Pull request

#8475 Make Scatterer-sunflare and Scatterer-config depend on Scatterer
  NetKAN/Scatterer-config.netkan
  NetKAN/Scatterer-sunflare.netkan
  NetKAN/Scatterer.netkan
Labels: Fix relationships

#8479 Add GRAPES
  NetKAN/GRAPES.netkan
Labels: Easy, Mod-request, Pull request

#8480 Add PlanetOrigins
  NetKAN/PlanetOrigins.netkan
Labels: Easy, Mod-request, Pull request

#8481 Remove UnKerballedStart and ProbesBeforeCrew from TechTreeKompacted conflicts
  NetKAN/TechTreeKompacted.netkan
Labels: Fix relationships, Pull request

#8482 vref for FelineUtilityRovers
  NetKAN/FelineUtilityRovers.netkan
Labels: Easy, Fix compatibility, Pull request

#8483 Pin min compat of KerbalSpacePonies
  NetKAN/KerbalSpacePonies.netkan
Labels: Easy, Fix compatibility, Pull request

#8485 Force v for BDArmoryForRunwayProject
  NetKAN/BDArmoryForRunwayProject.netkan
Labels: Fix versioning, Pull request

#8487 New dep for KerbinPlacePack
  NetKAN/KerbinPlacePack.netkan
Labels: Easy, Fix relationships, Pull request

#8489 Update LFOBalancer kref
  NetKAN/LFOBalancer.netkan
Labels: Easy, Pull request

#8488 Update moved metanetkans
  NetKAN/AlcubierreStandalone.netkan
  NetKAN/CommunityCategoryKit.netkan
  NetKAN/CommunityResourcePack.netkan
  NetKAN/Karbonite.netkan
  NetKAN/Konstruction.netkan
  NetKAN/MalemuteRover.netkan
  NetKAN/SoundingRockets.netkan
  NetKAN/UKS.netkan
  NetKAN/USI-ART.netkan
  NetKAN/USI-Core.netkan
  NetKAN/USI-EXP.netkan
  NetKAN/USI-FTT.netkan
  NetKAN/USI-LS.netkan
  NetKAN/USI-NuclearRockets.netkan
  NetKAN/USITools.netkan
Labels: Easy, Pull request

#8490 Update BetterTimeWarpCont kref
  NetKAN/BetterTimeWarpCont.netkan
Labels: Easy, Pull request

#8492 Update BargainRocketsCont kref
  NetKAN/BargainRocketsCont.netkan
Labels: Easy, Pull request

#8491 Update CustomPreLaunchChecks kref
  NetKAN/CustomPreLaunchChecks.netkan
Labels: Easy, Pull request

#8493 Unfreeze StandardPropulsionSystems
  NetKAN/StandardPropulsionSystems.frozen
  NetKAN/StandardPropulsionSystems.netkan
Labels: Easy, In progress, Mod-request, Pull request

#8494 vref for StandardPropulsionSystems
  NetKAN/StandardPropulsionSystems.netkan
Labels: Easy, Fix compatibility, Pull request

#8495 Add VertikalSpeedIndicator
  NetKAN/VertikalSpeedIndicator.netkan
Labels: Easy, Mod-request, Pull request

#8450 Add BoosterGuidance
  NetKAN/BoosterGuidance.netkan
Labels: Mod-request, Pull request

#8499 Add KSP-Data-Export
  NetKAN/KSP-Data-Export.netkan
Labels: Mod-request, Pull request

#8502 Freeze B5
  NetKAN/B5.frozen
Labels: Easy, Pull request

#8505 Vref for ComfortableLanding
  NetKAN/ComfortableLanding.netkan
Labels: Easy, Fix compatibility, Pull request

#8504 Set Kerbal Flight Indicators repo back to DaMichel's
  NetKAN/KerbalFlightIndicators.netkan
Labels: Easy, Pull request, Waiting on PR creator
