Repository KSP-CKAN/NetKAN, pull requests merged in 2021-10, with the labels that each got.

#8789 Freeze IR-Model-Rework
  NetKAN/IR-Model-Rework-Core.frozen
  NetKAN/IR-Model-Rework-Expansion.frozen
  NetKAN/IR-Model-Rework-Utility.frozen
Labels: Freeze

#8794 Update KerwisChinaAerospacePack.netkan
  NetKAN/KerwisChinaAerospacePack.netkan
Labels: Pull request

#8836 Override compat of StrangeNewWorlds v0.1.2
  NetKAN/StrangeNewWorlds.netkan
Labels: Pull request, Fix compatibility
