Repository KSP-CKAN/NetKAN, pull requests merged in 2021-05, with the labels that each got.

#8509 Telemagic no longer has crafts, now has a version file
  NetKAN/Telemagic.netkan
Labels: Easy, Fix compatibility, Fix install, Pull request

#8511 Update KerbalMiniShuttle install
  NetKAN/KerbalMiniShuttle.netkan
Labels: Fix install, Pull request

#8512 Add CompletelyNonAggressiveRocketry
  NetKAN/CompletelyNonAggressiveRocketry.netkan
Labels: Mod-request, Pull request

#8514 Add USSDiscovery
  NetKAN/USSDiscovery.netkan
Labels: Mod-request, Pull request

#8517 Add recent mods from SpaceDock
  NetKAN/BirthOfTime.netkan
  NetKAN/BreakingGroundPropellerRebalance.netkan
  NetKAN/PLUM.netkan
Labels: Mod-request, Pull request

#8523 Fix KerbalTelemetry install
  NetKAN/KerbalTelemetry.netkan
Labels: Easy, Fix install, Pull request

#8527 Install ImprovedTreeEnginePlacement extras
  NetKAN/ImprovedTreeEnginePlacement.netkan
Labels: Fix install, Fix relationships, Pull request

#8528 MM dep for KSP-PartVolume
  NetKAN/KSP-PartVolume.netkan
Labels: Easy, Fix relationships, Pull request

#8532 Create StagedAnimation.netkan
  NetKAN/StagedAnimation.netkan
Labels: Mod-request, Pull request

#8533 Add CSITechTree and WorkingUnderwaterLite
  NetKAN/CrusoeSpaceIndustriesTechTree.netkan
  NetKAN/WorkingUnderwaterLite.netkan
Labels: Mod-request, Pull request

#8501 Add No Texture mods
  NetKAN/No-Texture-Atlas-5.netkan
  NetKAN/No-Texture-CST-100.netkan
Labels: In progress, Mod-request, Pull request

#8538 Add JNSQ-RealDate and GreenKerbs
  NetKAN/GreenKerbs.netkan
  NetKAN/JNSQ-RealDate.netkan
Labels: Easy, In progress, Mod-request, Pull request

#8537 Update RealAntennas.netkan
  NetKAN/RealAntennas.netkan
Labels: Easy, Fix relationships, Pull request

#8542 Add BenjisHardwiredLogic
  NetKAN/BenjisHardwiredLogic.netkan
Labels: Easy, Mod-request, Pull request

#8547 Update SDHI-StrobeOMatic compatibility
  NetKAN/SDHI-StrobeOMatic.netkan
Labels: Easy, Fix compatibility, Pull request

#8550 WorkingUnderwaterLite no longer has a SPH folder
  NetKAN/WorkingUnderwaterLite.netkan
Labels: Easy, Fix install, Pull request

#8552 Final SpaceDock catch-up 🤞
  NetKAN/AtomicTechFlags.netkan
  NetKAN/AutoHibernate.netkan
  NetKAN/ElectronStrongbackErector.netkan
Labels: Easy, Mod-request, Pull request
