Repository KSP-CKAN/NetKAN, pull requests merged in 2021-08, with the labels that each got.

#8689 Make RSS recommend RSSVE-Textures
  NetKAN/RealSolarSystem.netkan
Labels: Fix relationships, Pull request

#8691 Fix KerbalMiniShuttle install
  NetKAN/KerbalMiniShuttle.netkan
Labels: Easy, Fix install, Fix relationships, Pull request

#8692 Pin min compat of KSP-Data-Export
  NetKAN/KSP-Data-Export.netkan
Labels: Fix compatibility, Pull request

#8697 Continue unfreezing MiniSampleReturnCapsule
  NetKAN/MiniSampleReturnCapsule.netkan
Labels: Fix relationships, Easy, Pull request

#8699 Fix TrekDrive install and depends
  NetKAN/TrekDrive.netkan
Labels: Fix relationships, Fix install, Pull request

#8700 Correct minversion for Scatterer
  NetKAN/Scatterer-config.netkan
  NetKAN/Scatterer-sunflare.netkan
  NetKAN/Scatterer.netkan
Labels: Blocked-on-Other, Blocked-on-Mod-Author

#8704 Upload repo artifacts for pull requests
  .github/workflows/inflate.yml
Labels: Pull request

#8706 Provide unique identifier for the full KSPBurst module
  NetKAN/KSPBurst.netkan
Labels: Fix relationships, Easy, Pull request

#8710 Add GemstoneLV
  NetKAN/GemstoneLV.netkan
Labels: Mod-request, Pull request

#8716 Add missing dependencies for CanaveralPads
  NetKAN/CanaveralPads.netkan
Labels: Fix relationships

#8718 Add Alarm Enhancements
  NetKAN/AlarmEnhancements.netkan
Labels: Mod-request, Pull request

#8720 Create SimpleRepaint.netkan
  NetKAN/SimpleRepaint.netkan
Labels: Mod-request, Pull request

#8722 Revert Scatterer-sunflare and Scatterer-config dependency on Scatterer
  NetKAN/Scatterer-config.netkan
  NetKAN/Scatterer-sunflare.netkan
Labels: Fix relationships, Pull request

#8723 Upload .ckans instead of .repo/metadata.tar.gz as workflow artifact
  .github/workflows/inflate.yml
Labels: Pull request, Bug

#8726 Pin min compat for PanoceanCanal
  NetKAN/PanoceanCanal.netkan
Labels: Pull request, Fix compatibility

#8737 Fix dbent metanetkan branches
  NetKAN/HotSpot.netkan
  NetKAN/PlaneMode.netkan
Labels: Easy, Pull request

#8739 Update StockWaterfallEffects compatibility for 0.5.2
  NetKAN/StockWaterfallEffects.netkan
Labels: Pull request, Fix compatibility
