Repository KSP-CKAN/NetKAN, pull requests merged in 2022-07, with the labels that each got.

#9192 Unfreeze BakerOperatingSystem
  NetKAN/BakerOperatingSystem.netkan
Labels: Pull request, Fix compatibility

#9197 Vref for PrakasaAeroworks
  NetKAN/PrakasaAeroworks.netkan
Labels: Easy, Pull request, Fix compatibility

#9193 ROCapsules use remote netkan
  NetKAN/ROCapsules.netkan
Labels: Easy, Pull request

#9200 Remove PlanetShine's repository override
  NetKAN/PlanetShine.netkan
Labels: Easy, Pull request

#9203 Vref for DraggableAltimeter
  NetKAN/DraggableAltimeter.netkan
Labels: Easy, Pull request, Fix compatibility

#9202 Add Kopernicus dependency on Harmony2
  NetKAN/Kopernicus.netkan
Labels: Fix relationships, Easy, Pull request

#9205 Fix BakerOperatingSystem install
  NetKAN/BakerOperatingSystem.netkan
Labels: Easy, Fix install, Pull request

#9206 Update Kethane
  NetKAN/Kethane.netkan
Labels: Pull request

#9214 Fix SRBWaterfallEffects install yet again
  NetKAN/SRBWaterfallEffects.netkan
Labels: Easy, Fix install, Pull request

#9219 Add KSPCF as dependency to ProceduralParts
  NetKAN/ProceduralParts.netkan
Labels: Fix relationships

#9218 Add ROHeatshields to CKAN
  NetKAN/ROHeatshields.netkan
Labels: Mod-request

#9224 Spectra Vibrant Sunsets and install fix
  NetKAN/Spectra-VibrantSunsets.netkan
  NetKAN/Spectra.netkan
Labels: Mod-request, Fix relationships, Easy, Fix install, Pull request

#9225 Fix AtomicTechIncJunkyards install
  NetKAN/AtomicTechIncJunkyards.netkan
Labels: Fix install, Pull request

#9226 MoldaviteMachines updates
  NetKAN/MoldaviteMachines.netkan
  NetKAN/MoldaviteMachinesKerbalism.netkan
Labels: Mod-request, Fix relationships, Easy, Pull request

#9227 ContractConfigurator adopted by KSP-RO
  NetKAN/ContractConfigurator-RO.frozen
  NetKAN/ContractConfigurator.netkan
Labels: Mod-request, Easy, Pull request

#9231 Update Spectra-VibrantSunsets.netkan
  NetKAN/Spectra-VibrantSunsets.netkan
Labels: Fix relationships, Pull request

#9233 Create Spectra-JoolShineOnLaythe.netkan
  NetKAN/Spectra-JoolShineOnLaythe.netkan
Labels: Mod-request, Pull request

#9234 Create Spectra-KerbinLaytheSnow.netkan
  NetKAN/Spectra-KerbinLaytheSnow.netkan
Labels: Mod-request, Pull request

#9238 Fix Spectras Extras installs
  NetKAN/Spectra-JoolShineOnLaythe.netkan
  NetKAN/Spectra-KerbinLaytheSnow.netkan
Labels: Easy, Fix install, Pull request

#9235 Create Spectra-MinmusScatterer.netkan
  NetKAN/Spectra-MinmusScatterer.netkan
Labels: Mod-request, Pull request

#9236 Create Spectra-MinmusGeysers.netkan
  NetKAN/Spectra-MinmusGeysers.netkan
Labels: Mod-request, Pull request

#9239 Install whole subfolders of Spectra Extras
  NetKAN/Spectra-JoolShineOnLaythe.netkan
  NetKAN/Spectra-KerbinLaytheSnow.netkan
  NetKAN/Spectra-MinmusGeysers.netkan
  NetKAN/Spectra-MinmusScatterer.netkan
  NetKAN/Spectra-VibrantSunsets.netkan
Labels: Fix install, Pull request

#9237 Update and rename RVE64kKerbinCloudsforSpectra.netkan to Spectra-RVE6…
  NetKAN/RVE64kKerbinCloudsforSpectra.netkan
  NetKAN/Spectra-RVE64kKerbinClouds.netkan
Labels: Pull request

#9243 Fix SRBWaterfallEffects install again again again
  NetKAN/SRBWaterfallEffects.netkan
Labels: Fix install, Pull request
