Repository KSP-CKAN/NetKAN, pull requests merged in 2022-10, with the labels that each got.

#9366 Add Custom Categories
  NetKAN/CustomCategories.netkan
Labels: Mod-request, Pull request

#9371 Add TourismExpanded
  NetKAN/TourismExpanded.netkan
Labels: Mod-request, Blocked-on-Mod-Author, Pull request

#9374 Update TourismExpanded name
  NetKAN/TourismExpanded.netkan
Labels: Easy, Pull request

#9385 Add SIMPLEXResources
  NetKAN/SIMPLEXResources.netkan
Labels: Mod-request, Pull request

#9367 Unfreeze UnKerballedStart
  NetKAN/UnKerballedStart.netkan
Labels: Waiting on PR creator, Pull request, Freeze

#9393 Add BluedogDB deps
  NetKAN/BluedogDB.netkan
Labels: Mod-enhancement, Fix relationships, Easy, Pull request, Waiting for new mod release

#9395 Add ShuttleOrbiterConstructionKitRecolored
  NetKAN/ShuttleOrbiterConstructionKitRecolored.netkan
Labels: Mod-request, Pull request

#9398 Update EuropeanSpaceAgencyRocketKit install
  NetKAN/EuropeanSpaceAgencyRocketKit.netkan
Labels: Easy, Fix install, Pull request

#9402 Updates Pathfinder to recommend Buffalo 2 and not depend on Buffalo
  NetKAN/Pathfinder.netkan
Labels: Fix relationships, Pull request

#9399 Add netkan for kOS-KerbalEngineer
  NetKAN/kOS-KerbalEngineer.netkan
Labels: Mod-request, Pull request

#9408 Add LunarTransferPlanner
  NetKAN/LunarTransferPlanner.netkan
Labels: Mod-request, Pull request

#9409 Unfreeze OrbitalSurveyPlus
  NetKAN/OrbitalSurveyPlus.frozen
  NetKAN/OrbitalSurveyPlus.netkan
Labels: Pull request, Freeze

#9410 Add ROEnginesExtended to CKAN
  NetKAN/ROEnginesExtended.netkan
Labels: Mod-request, Pull request
