Repository KSP-CKAN/NetKAN, pull requests merged in 2022-11, with the labels that each got.

#9413 Add BDArmoryExtended
  NetKAN/BDArmoryExtended.netkan
Labels: Mod-request, Pull request

#9416 Freeze AtomicTechKerbalDietPills
  NetKAN/AtomicTechKerbalDietPills.frozen
Labels: Easy, Pull request, Freeze

#9415 Update DepthMask netkan file in preparation for next patch
  NetKAN/DepthMask.netkan
Labels: Fix install, Pull request, Waiting for new mod release

#9417 Fix WernhersOldBits install
  NetKAN/WernhersOldBits.netkan
Labels: Fix install, Pull request, Fix compatibility

#9419 Create PartInfoInPAW.netkan
  NetKAN/PartInfoInPAW.netkan
Labels: Mod-request, Pull request

#9421 Fix KerbalTelemetry install
  NetKAN/KerbalTelemetry.netkan
Labels: Fix install, Pull request

#9427 Update kOS-Astrogator dep min version for Astrogator
  NetKAN/kOS-Astrogator.netkan
Labels: Fix relationships, Easy, Pull request

#9428 Add WildBlueCore dep to Sandcastle
  NetKAN/Sandcastle.netkan
Labels: Fix relationships, Easy, Pull request

#9432 Create BluedogDB Extras
  NetKAN/BluedogDB-CommunityCategoryKit.netkan
  NetKAN/BluedogDB-Methalox.netkan
  NetKAN/BluedogDB-RealNames.netkan
Labels: Mod-enhancement, Mod-request, Pull request

#9435 Filter Scale_Redist.dll out of TweakScale
  NetKAN/TweakScale.netkan
Labels: Fix install, Pull request

#9430 Add ShuttlePathfinderOrbiterConstructionKit
  NetKAN/ShuttlePathfinderOrbiterConstructionKit.netkan
Labels: Mod-request, Pull request

#9438 Remove fake ZeroMiniAVC dependencies from LGG's mods
  NetKAN/ClickThroughBlocker.netkan
  NetKAN/ToolbarController.netkan
Labels: Fix relationships, Discussion needed, Easy, Pull request

#9446 Fix NeidonPlus install
  NetKAN/NeidonPlus.netkan
Labels: Easy, Fix install, Pull request

#9447 Fix NeidonPlus install again
  NetKAN/NeidonPlus.netkan
Labels: Easy, Fix install, Pull request

#9448 MM dep for BDArmoryExtended
  NetKAN/BDArmoryExtended.netkan
Labels: Fix relationships, Easy, Pull request

#9449 Update KASAS1LoadingScreens install
  NetKAN/KASAS1LoadingScreens.netkan
Labels: Easy, Fix install, Pull request
