Repository KSP-CKAN/NetKAN, pull requests merged in 2022-05, with the labels that each got.

#9101 Fix SRBWaterfallEffects install
  NetKAN/SRBWaterfallEffects.netkan
Labels: Easy, Fix install, Pull request

#9102 force_v for OblivionAerospace
  NetKAN/OblivionAerospace.netkan
Labels: Pull request, Fix versioning

#8515 Add GalaxiesUnbound and friends
  NetKAN/GalaxiesUnbound-AlienWorlds.netkan
  NetKAN/GalaxiesUnbound-AlphaCentauri.netkan
  NetKAN/GalaxiesUnbound-Core.netkan
  NetKAN/GalaxiesUnbound-EpsilonEridani.netkan
  NetKAN/GalaxiesUnbound-Lich.netkan
  NetKAN/GalaxiesUnbound-Luhman16.netkan
  NetKAN/GalaxiesUnbound-Parts.netkan
  NetKAN/GalaxiesUnbound-Sirius.netkan
  NetKAN/GalaxiesUnbound-StellarAdventures.netkan
  NetKAN/GalaxiesUnbound-TauCeti.netkan
  NetKAN/GalaxiesUnbound-TeegardensStar.netkan
  NetKAN/GalaxiesUnbound-Trappist-1.netkan
  NetKAN/GalaxiesUnbound-WorldsofFire.netkan
Labels: Mod-request, Pull request

#9110 Limit CraftManager compatibility to KSP 1.8-1.9
  NetKAN/CraftManager.netkan
Labels: Pull request, Fix compatibility

#9114 Add TweakScale-Redist, filter DLL from IR and FAR
  NetKAN/FerramAerospaceResearchContinued.netkan
  NetKAN/InfernalRoboticsNext.netkan
  NetKAN/InfernalRoboticsRealismOverhaul.netkan
  NetKAN/TweakScale-Redist.netkan
  NetKAN/TweakScale.netkan
Labels: Fix install, Pull request

#9118 Update SpaceDustUnbound's relationships
  NetKAN/SpaceDustUnbound.netkan
Labels: Fix relationships, Easy, Pull request

#9120 GPOSpeedPump under new management!
  NetKAN/GPOSpeedPump.netkan
Labels: Pull request

#9123 MM dep for FoxDefenseContracts
  NetKAN/FoxDefenseContracts.netkan
Labels: Fix relationships, Easy, Pull request

#9124 Remove FoxDefenseContracts install workarounds
  NetKAN/FoxDefenseContracts.netkan
Labels: Fix install, Pull request

#9125 MM dep for J20R
  NetKAN/J20R.netkan
Labels: Fix relationships, Pull request

#9126 Require BackgroundResources for DeepFreeze
  NetKAN/DeepFreeze.netkan
Labels: Fix relationships, Easy, Pull request

#9127 Move Scatterer to dependencies of KHNS
  NetKAN/KerbolsHumbleNeighboringStars.netkan
Labels: Fix relationships, Easy

#9128 KHNS ships with a full Scatterer config & sunflare, provide them
  NetKAN/KerbolsHumbleNeighboringStars.netkan
Labels: Fix relationships, Pull request

#9133 Craft installs for FlyingSaucers
  NetKAN/FlyingSaucers.netkan
Labels: Easy, Fix install, Pull request

#9140 Fix SigmasRSSTUFXProfiles install
  NetKAN/SigmasRSSTUFXProfiles.netkan
Labels: Easy, Fix install, Pull request
