Repository KSP-CKAN/NetKAN, pull requests merged in 2022-08, with the labels that each got.

#9244 Let Spectra's internal ckan files set its relationships
  NetKAN/Spectra-JoolShineOnLaythe.netkan
  NetKAN/Spectra-KerbinLaytheSnow.netkan
  NetKAN/Spectra-MinmusGeysers.netkan
  NetKAN/Spectra-MinmusScatterer.netkan
  NetKAN/Spectra-VibrantSunsets.netkan
  NetKAN/Spectra.netkan
Labels: Fix relationships, Easy, Pull request

#9251 Fix Spectra add-on installs
  NetKAN/Spectra-JoolShineOnLaythe.netkan
  NetKAN/Spectra-KerbinLaytheSnow.frozen
  NetKAN/Spectra-MinmusGeysers.frozen
  NetKAN/Spectra-MinmusScatterer.frozen
  NetKAN/Spectra-VibrantSunsets.netkan
Labels: Fix install, Pull request

#9254 Remove redundant recommends from AutomatedScreenshots
  NetKAN/AutomatedScreenshots.netkan
Labels: Fix relationships, Easy, Pull request

#9255 Freeze KASAFlagPackandTUFXProfile
  NetKAN/KASAFlagPackandTUFXProfile.frozen
Labels: Pull request, Freeze

#9256 Add FreeLaunchClamps
  NetKAN/AlmostFreeLaunchClamps.frozen
  NetKAN/AlmostFreeLaunchClamps.netkan
Labels: Mod-request, Pull request

#9257 Add DeployableInventory
  NetKAN/DeployableInventory.netkan
Labels: Mod-request, Pull request

#9260 Add recommended mods | SWE
  NetKAN/SRBWaterfallEffects.netkan
Labels: Fix relationships, Easy, Pull request

#9262 Switch to main Shabby version file
  NetKAN/Shabby.netkan
Labels: Pull request

#9278 Update Scatterer for PRVE to 0.0838
  NetKAN/PhotoRealisticVisualEnhancement-LowRes.netkan
  NetKAN/PhotoRealisticVisualEnhancement.netkan
Labels: Fix relationships, Pull request

#9281 Freeze old Draggable* mods
  NetKAN/DraggableAltimeter.frozen
  NetKAN/DraggableNavball.frozen
Labels: Easy, Pull request, Freeze

#9285 Add conflicts to ErsteSterne and KHNS for provides
  NetKAN/ErsteSterne.netkan
  NetKAN/KerbolsHumbleNeighboringStars.netkan
Labels: Fix relationships, Pull request

#9289 Unfreeze SuperfluousNodes
  NetKAN/SuperfluousNodes.frozen
  NetKAN/SuperfluousNodes.netkan
Labels: Pull request

#9293 Switch FoxDefenseContracts to BDArmoryForRunwayProject
  NetKAN/FoxDefenseContracts.netkan
Labels: Fix relationships, Easy, Pull request

#9300 Vref for Targetron
  NetKAN/Targetron.netkan
Labels: Easy, Pull request, Fix compatibility

#9310 Buffalo2 and WildBlueCore NetKAN Additions
  NetKAN/Buffalo2.netkan
  NetKAN/Sandcastle.netkan
  NetKAN/WildBlueCore.netkan
Labels: Mod-request, Pull request
