Repository KSP-CKAN/NetKAN, pull requests merged in 2022-02, with the labels that each got.

#8992 Set resources.remote-avc for mods with bad version file URL properties
  NetKAN/CollisionFXReUpdated.netkan
  NetKAN/KSCExtended.netkan
  NetKAN/MandatoryRCS.netkan
  NetKAN/MandatoryRCSPartPack.netkan
  NetKAN/RealHeat.netkan
  NetKAN/TransparentPods.netkan
Labels: Easy, Pull request, Fix compatibility

#9001 Change GasGiantsEnhanced dep on RSS to rec
  NetKAN/GasGiantsEnhanced.netkan
Labels: Fix relationships, Easy, Pull request

#9002 Fix StockDepthMaskConfig find_regexp
  NetKAN/StockDepthMaskConfig.netkan
Labels: Fix install, Pull request

#9004 Unfreeze RosterManager
  NetKAN/RosterManager.frozen
  NetKAN/RosterManager.netkan
Labels: Easy, Pull request

#9005 Switch KerbalFlightIndicators to PapaJoesSoup fork
  NetKAN/KerbalFlightIndicators.netkan
Labels: Easy, Pull request

#9011 Switch PlanetShine to PapaJoesSoup fork
  NetKAN/PlanetShine-Config-Default.netkan
  NetKAN/PlanetShine.netkan
Labels: Easy, Pull request

#9017 Add MM dep to PlanetInfoPlus
  NetKAN/PlanetInfoPlus.netkan
Labels: Fix relationships, Easy, Pull request

#9020 MM dep for Mk-X
  NetKAN/Mk-X.netkan
Labels: Fix relationships, Easy, Pull request
