Repository KSP-CKAN/NetKAN, pull requests merged in 2022-03, with the labels that each got.

#9015 Add PhotoRealisticVisualEnhancement
  NetKAN/PhotoRealisticVisualEnhancement-64k.netkan
  NetKAN/PhotoRealisticVisualEnhancement.netkan
Labels: In progress, Pull request

#9024 Create Reviva.netkan
  NetKAN/Reviva.netkan
Labels: Mod-request, Pull request

#9025 Fix BuranEnergia install
  NetKAN/BuranEnergia.netkan
Labels: Fix install, Pull request

#9030 Fix SRBWaterfallEffects install
  NetKAN/SRBWaterfallEffects.netkan
Labels: Easy, Fix install, Pull request

#8922 Add Conformal Decals and Shabby
  NetKAN/ConformalDecals.netkan
  NetKAN/Shabby.netkan
Labels: Mod-request, Pull request

#9043 Suggest stock configs for ModuleDepthMask
  NetKAN/DepthMask.netkan
  NetKAN/StockDepthMaskConfig.netkan
Labels: Fix relationships, Pull request

#9045 Switch Rocket Sound Enhancment - Default repo, rename
  NetKAN/RocketSoundEnhancement-Config-Default.netkan
  NetKAN/RocketSoundEnhancement.netkan
Labels: Mod-request, Fix install, Pull request

#9050 Update krefs for ValiZockt name change
  NetKAN/RealFuels-Stock.netkan
  NetKAN/SmartDockingAid.netkan
Labels: Easy, Pull request

#9049 Add TransferWindowPlanner - Fork
  NetKAN/TransferWindowPlannerFork.netkan
Labels: Mod-request, Pull request
