Repository KSP-CKAN/NetKAN, pull requests merged in 2022-09, with the labels that each got.

#9316 Fix RadialHeatShields install location
  NetKAN/RadialHeatShields.netkan
Labels: Easy, Fix install, Pull request

#9318 Update FerramAerospaceResearchContinued dependencies
  NetKAN/FerramAerospaceResearchContinued.netkan
Labels: Fix relationships, Pull request, Waiting for new mod release

#9321 Make Parallax 2.0.0 modules conflict with <2.0.0 releases
  NetKAN/Parallax-StockScatterTextures.netkan
  NetKAN/Parallax-StockTextures.netkan
  NetKAN/Parallax.netkan
Labels: Pull request, Fix compatibility

#9323 Fix Parallax conflict version deps
  NetKAN/Parallax-StockScatterTextures.netkan
  NetKAN/Parallax-StockTextures.netkan
  NetKAN/Parallax.netkan
Labels: Fix relationships, Easy, Pull request

#9326 Add Starilex Mk1 Needle IVA
  NetKAN/StarilexMk1NeedleIVA.netkan
Labels: Mod-request, Blocked-on-CKAN-Feature, Pull request

#9327 Add resources.spacedock to StarilexMk1NeedleIVA
  NetKAN/StarilexMk1NeedleIVA.netkan
Labels: Easy, Pull request

#9332 Buffalo 2 requires Kerbal Actuators
  NetKAN/Buffalo2.netkan
Labels: Fix relationships, Pull request

#9333 Adds sample craft to Buffalo 2
  NetKAN/Buffalo2.netkan
Labels: Easy, Fix install, Pull request

#9336 Post-migration SpaceDock catch-up 1
  NetKAN/KerbalFlightworksCompany.netkan
  NetKAN/OblivionBubblePatrolCraft.netkan
Labels: Mod-request, Pull request

#9337 Post-migration SpaceDock catch-up 2
  NetKAN/ColorChangingSmokeGenerator.netkan
  NetKAN/KerbalBall.netkan
  NetKAN/LudicrousParts.netkan
  NetKAN/ShadoUFO.netkan
  NetKAN/StockalikeAircraftCarrierDecks.netkan
Labels: Mod-request, Pull request

#9339 Add MM dep for KerbinSideRemasteredTLA
  NetKAN/KerbinSideRemasteredTLA.netkan
Labels: Fix relationships, Pull request

#9340 Add BetterKerbol
  NetKAN/BetterKerbol.netkan
  NetKAN/BetterKerbolRescale.netkan
Labels: Mod-request, Pull request

#9341 Add Kerbal-Kountries
  NetKAN/KerbalKountries.netkan
Labels: Mod-request, Pull request

#9343 Fix ModeratelyPlaneRelated install
  NetKAN/ModeratelyPlaneRelated.netkan
Labels: Easy, Fix install, Pull request

#9347 Get DMTanks repositories from SpaceDock again
  NetKAN/DMTanks-AeroRTG.netkan
  NetKAN/DMTanks-CargoBays.netkan
  NetKAN/DMTanks-Fuselage.netkan
  NetKAN/DMTanks-SphericalTanks.netkan
Labels: Easy, Pull request

#9344 Add ExtremePlaneContracts
  NetKAN/ExtremePlaneContracts.netkan
Labels: Mod-request, Pull request

#9348 Override bad version file URL properties
  NetKAN/HooliganLabsAirships.netkan
  NetKAN/MOTHS.netkan
  NetKAN/PicoPortShielded.netkan
  NetKAN/RSSVE-HR.netkan
  NetKAN/RSSVE-LR.netkan
  NetKAN/StarshipLaunchExpansion.netkan
  NetKAN/USI-NuclearRockets.netkan
  NetKAN/WildBlueCore.netkan
Labels: Pull request, Fix versioning

#9349 Add KcalbelohSystem
  NetKAN/KcalbelohSystem.netkan
Labels: Mod-request, Pull request

#9350 Freeze KcalbelohSystem
  NetKAN/KcalbelohSystem.frozen
Labels: Pull request, Freeze

#9351 Add FruitGoose as author to FruitGoose's mods
  NetKAN/APPLE.netkan
  NetKAN/FIG.netkan
  NetKAN/GRAPES.netkan
  NetKAN/LIME.netkan
  NetKAN/MANGO.netkan
  NetKAN/ORANGE.netkan
  NetKAN/PEAR.netkan
  NetKAN/PLUM.netkan
  NetKAN/PRUNES.netkan
  NetKAN/VertikalSpeedIndicator.netkan
Labels: Easy, Pull request

#9354 Add Building Blocker
  NetKAN/BuildingBlocker.netkan
Labels: Mod-request, Easy, Pull request

#9355 Freeze UnKerballedStart
  NetKAN/UnKerballedStart.frozen
Labels: Pull request, Freeze

#9357 Add kOS-Astrogator.netkan
  NetKAN/kOS-Astrogator.netkan
Labels: Mod-request, Pull request

#9358 Specify minimum version of Astrogator for kOS-Astrogator
  NetKAN/kOS-Astrogator.netkan
Labels: Fix relationships, Easy, Pull request
