Repository KSP-CKAN/NetKAN, pull requests merged in 2023-03, with the labels that each got.

#9590 Update StarshipExpansionProject Metadata
  NetKAN/StarshipExpansionProject.netkan
  NetKAN/StarshipExpansionProjectIVA.netkan
Labels: Mod-request, Fix relationships, Pull request

#9599 Fix MinmarKerbinRings installs
  NetKAN/MinmarKerbinRings-Classic.netkan
  NetKAN/MinmarKerbinRings-New.netkan
Labels: Easy, Fix install, Pull request

#9602 Freeze JakesKonstructStatics
  NetKAN/JakesKonstructStatics.frozen
Labels: Pull request, Freeze

#9609 Fix MinmarKerbinRings-New install
  NetKAN/MinmarKerbinRings-New.netkan
Labels: Fix install, Pull request

#9614 Fix ASET Consolidated installs
  NetKAN/MK12PodIVAReplacementbyASET.netkan
  NetKAN/Mk1CockpitIVAReplbyASET.netkan
  NetKAN/Mk1LanderCanIVAReplbyASET.netkan
Labels: Fix install, Pull request

#9550 Aviation Lights changed ownership.
  NetKAN/AviationLights.netkan
Labels: Mod-request, Pull request

#9613 Add EveOptimizedEngines
  NetKAN/EveOptimizedEngines.netkan
Labels: Mod-request, Blocked-on-Mod-Author, Pull request

#9611 Add FuelMyShip
  NetKAN/FuelMyShip.netkan
Labels: Pull request

#9612 Add Kerbalism-SystemHeat
  NetKAN/Kerbalism-FarFutureTechnologies.netkan
  NetKAN/Kerbalism-SystemHeat.netkan
Labels: Mod request

#9628 Add PlumeParty
  NetKAN/PlumeParty-StockConfigs.netkan
  NetKAN/PlumeParty.netkan
Labels: Mod request

#9633 Remove VesselView dep on JSIPartUtilities
  NetKAN/VesselView.netkan
Labels: Fix relationships

#9637 Add BDArmoryMultiplayer
  NetKAN/BDArmoryMultiplayer.netkan
Labels: Mod request

#9643 Update kRPC-MechJeb compatibility
  NetKAN/kRPC-MechJeb.netkan
Labels: Fix compatibility, Pull request
