Repository KSP-CKAN/NetKAN, pull requests merged in 2023-11, with the labels that each got.

#9824 unfreeze CAMk3BlockII as it had an update
  NetKAN/CAMk3BlockII.frozen
  NetKAN/CAMk3BlockII.netkan
Labels: Mod request, Freeze

#9831 Add ROUtils and RONoCareer
  NetKAN/RONoCareer.netkan
  NetKAN/ROUtils.netkan
Labels: Mod request

#9847 Vref for SuperfluousNodes
  NetKAN/SuperfluousNodes.netkan
Labels: Fix compatibility

#9851 Vref for KOSHUD
  NetKAN/KOSHUD.netkan
Labels: Fix compatibility

#9852 MM dep for StarshipExpansionProjectIVA
  NetKAN/StarshipExpansionProjectIVA.netkan
Labels: Fix relationships

#9853 Create RationalResourcesJetFamily.netkan
  NetKAN/RationalResourcesJetFamily.netkan
Labels: Mod request

#9854 Update dependencies of RationalResources addons
  NetKAN/RationalResourcesNuclearFamily.netkan
  NetKAN/RationalResourcesRCSFamily.netkan
Labels: Mod enhancement, Fix relationships

#9860 Force_v for KerbalKrashSystem.netkan
  NetKAN/KerbalKrashSystem.netkan
Labels: Fix versioning

#9858 Add kOS-Addons-Ferram
  NetKAN/kOS-AddOns-Ferram.netkan
Labels: Mod request, In progress

#9862 Freeze KSPArtemisSuit
  NetKAN/KSPArtemisSuit.frozen
Labels: Freeze
