Repository KSP-CKAN/NetKAN, pull requests merged in 2023-10, with the labels that each got.

#9814 Vref for SSTOProjectLPG
  NetKAN/SSTOProjectLPG.netkan
Labels: Easy, Fix compatibility

#9818 Force-allow KSPWheel on 1.12 while AVC is down
  NetKAN/KSPWheel.netkan
Labels: Fix compatibility

#9819 Update BakerOperatingSystem install
  NetKAN/BakerOperatingSystem.netkan
Labels: Fix install

#9822 Tundra mods netkan update
  NetKAN/TundraExploration.netkan
  NetKAN/TundraTechnologies.netkan
Labels: Fix relationships
