Repository KSP-CKAN/NetKAN, pull requests merged in 2023-08, with the labels that each got.

#9749 Freeze GalaxiesUnbound
  NetKAN/GalaxiesUnbound-AlienWorlds.frozen
  NetKAN/GalaxiesUnbound-AlphaCentauri.frozen
  NetKAN/GalaxiesUnbound-Core.frozen
  NetKAN/GalaxiesUnbound-EpsilonEridani.frozen
  NetKAN/GalaxiesUnbound-Lich.frozen
  NetKAN/GalaxiesUnbound-Luhman16.frozen
  NetKAN/GalaxiesUnbound-Parts.frozen
  NetKAN/GalaxiesUnbound-Sirius.frozen
  NetKAN/GalaxiesUnbound-StellarAdventures.frozen
  NetKAN/GalaxiesUnbound-StockClouds.frozen
  NetKAN/GalaxiesUnbound-TauCeti.frozen
  NetKAN/GalaxiesUnbound-TeegardensStar.frozen
  NetKAN/GalaxiesUnbound-Trappist-1.frozen
  NetKAN/GalaxiesUnbound-WorldsofFire.frozen
Labels: Freeze

#9750 Trim extra characters from SRBWaterfallEffects versions
  NetKAN/SRBWaterfallEffects.netkan
Labels: Fix versioning

#9755 Add MinorPlanetSampling
  NetKAN/MinorPlanetSampling.netkan
Labels: Mod request

#9756 New release of SciFiVisualEnhancements
  NetKAN/SciFiVisualEnhancements.netkan
Labels: Easy

#9757 Update RecycledParts recommendations
  NetKAN/RecycledParts.netkan
  NetKAN/RecycledPartsFTmNAtomicRockets.netkan
  NetKAN/RecycledPartsFTmNImprovedAtomicRockets.netkan
  NetKAN/RecycledPartsLVNClusters.netkan
  NetKAN/TeaKettleRCS.netkan
Labels: Fix relationships, Easy

#9758 Add EmbeddedKOSKirkuits
  NetKAN/EmbeddedKOSKirkuits.netkan
Labels: Mod request

#9769 Add missing dependency for ScrapYard
  NetKAN/ScrapYard.netkan
Labels: Fix relationships

#9766 Add PersistentThrustNavigator
  NetKAN/PersistentThrustNavigator.netkan
Labels: Mod request

#9774 Add StockAlarmClockDisabler
  NetKAN/StockAlarmClockDisabler.netkan
Labels: Mod request, Easy

#9772 Interstellar Fuel Switch depends on Community Resource PAck, otherwise there are errors
  NetKAN/InterstellarFuelSwitch.netkan
Labels: Support, Needs more info, Waiting on PR creator

#9775 Add ToolbarController depends for Trajectories
  NetKAN/Trajectories.netkan
Labels: Fix relationships, Easy

#9781 Add BetterScreenMessages
  NetKAN/BetterScreenMessages.netkan
Labels: Mod request, Easy, Blocked on mod author
