Repository KSP-CKAN/NetKAN, pull requests merged in 2023-07, with the labels that each got.

#9721 Add VertexMitchellNetravaliHeightMap as a dependency of Lazarus
  NetKAN/Lazarus.netkan
Labels: Fix relationships

#9722 Fix ModularRocketSystem install
  NetKAN/ModularRocketSystem.netkan
Labels: Fix install

#9723 Add Chinese Mod Patches
  NetKAN/ChineseModPatches.netkan
Labels: Mod request

#9725 Add WaterDrinker
  NetKAN/WaterDrinker.netkan
Labels: Mod request

#9730 Freeze KerbalDangerous
  NetKAN/KerbalDangerous.frozen
Labels: Freeze

#9734 Freeze mods hosted on broken taniwha.org server
  NetKAN/CustomBulkheadProfiles.frozen
  NetKAN/EarlyBird.frozen
  NetKAN/ExtraPlanetaryLaunchpads.frozen
  NetKAN/KerbalStats.frozen
  NetKAN/Kethane.frozen
  NetKAN/ModularFuelTanks.frozen
  NetKAN/Shabby.frozen
  NetKAN/SurveyTransponder.frozen
  NetKAN/TalisarParts.frozen
Labels: Freeze

#9741 Fix ChineseModPatches install
  NetKAN/ChineseModPatches.netkan
Labels: Fix install
