Repository KSP-CKAN/NetKAN, pull requests merged in 2023-12, with the labels that each got.

#9866 Improve Scatterer-config's abstract
  NetKAN/Scatterer-config.netkan
Labels: Easy

#9872 Freeze FirespitterExtended
  NetKAN/FirespitterExtended.frozen
Labels: Freeze

#9880 Vref for NavBallAdjustor
  NetKAN/NavBallAdjustor.netkan
Labels: Fix versioning

#9884 Vref for SaveConfirmationSound
  NetKAN/SaveConfirmationSound.netkan
Labels: Easy, Fix compatibility

#9887 Add first-person tag to known IVA mods
  NetKAN/ASETAvionics.netkan
  NetKAN/ASETProps.netkan
  NetKAN/B9-props.netkan
  NetKAN/DE-IVAExtension.netkan
  NetKAN/FreeIva.netkan
  NetKAN/HabTechProps.netkan
  NetKAN/KSAIVAUpgrade.netkan
  NetKAN/MK12PodIVAReplacementbyASET.netkan
  NetKAN/Mk1LanderCanIVAReplbyASET.netkan
  NetKAN/Mk3ShuttleMidDeckIVARefurbished.netkan
  NetKAN/NearFutureProps.netkan
  NetKAN/ProbeControlRoomRecontrolled.netkan
  NetKAN/QuickIVA.netkan
  NetKAN/RasterPropMonitor-Core.netkan
  NetKAN/RasterPropMonitor.netkan
  NetKAN/Reviva.netkan
  NetKAN/StarilexMk1NeedleIVA.netkan
  NetKAN/StarshipExpansionProjectIVA.netkan
  NetKAN/StationPartsExpansionRedux-IVAs.netkan
  NetKAN/TDProps.netkan
  NetKAN/ThroughTheEyesOfaKerbal.netkan
  NetKAN/VesselView-UI-RasterPropMonitor.netkan
  NetKAN/VexarpIVA.netkan
  NetKAN/kOSPropMonitor.netkan
Labels: Mod enhancement, Discussion needed

#9889 Add new dependencies for ArtemisConstructionKit
  NetKAN/ArtemisConstructionKit.netkan
Labels: Fix relationships, Easy

#9893 Make WBI ClassicStock, Pristine, and Simplified play modes conflict with CRP
  NetKAN/WildBlue-PlayMode-ClassicStock.netkan
  NetKAN/WildBlue-PlayMode-Pristine.netkan
  NetKAN/WildBlue-PlayMode-Simplified.netkan
Labels: Fix relationships
