Repository KSP-CKAN/NetKAN, pull requests merged in 2023-09, with the labels that each got.

#9784 Add Kraken Console
  NetKAN/KrakenConsole.netkan
Labels: Mod request

#9792 Add PerSaveScreenshots
  NetKAN/PerSaveScreenshots.netkan
Labels: Mod request

#9795 Freeze RealisticStockOPMSystem
  NetKAN/RealisticStockOPMSystem.frozen
Labels: Freeze

#9796 Update AstraRocket3TransporterErector install
  NetKAN/AstraRocket3TransporterErector.netkan
Labels: Easy, Fix install

#9803 new mod "Payload Retention System - Next"
  NetKAN/PayloadRetentionSystemNext.netkan
Labels: Mod request

#9806 Make KerbalField depend on the virtual BDArmory identifier
  NetKAN/KerbalField.netkan
Labels: Fix relationships, Blocked on mod author

#9810 Put more specific Parallax texture dependencies first
  NetKAN/Parallax-StockScatterTextures.netkan
  NetKAN/Parallax-StockTextures.netkan
Labels: Fix relationships
