Repository KSP-CKAN/NetKAN, pull requests merged in 2023-02, with the labels that each got.

#9497 Update SRBWaterfallEffects.netkan
  NetKAN/SRBWaterfallEffects.netkan
Labels: Fix relationships, Pull request

#9556 Unfreeze OtherWorlds
  NetKAN/OtherWorlds.frozen
  NetKAN/OtherWorlds.netkan
Labels: Mod-request, Pull request

#9557 Fix SpaceY-Lifters install
  NetKAN/SpaceY-Lifters.netkan
Labels: Fix install, Pull request

#9567 Make IXSWarpshipOS depend on warp drive mods
  NetKAN/IXSWarpshipOS.netkan
  NetKAN/WarpDrive.netkan
Labels: Fix relationships, Pull request

#9572 Freeze No-Texture-Atlas-5
  NetKAN/No-Texture-Atlas-5.frozen
Labels: Freeze

#9521 Create KeridianDynamics.netkan
  NetKAN/KeridianDynamicsVesselAssembly.frozen
  NetKAN/KeridianDynamicsVesselAssembly.netkan
Labels: Mod-request, Pull request

#9522 Rusty Star Rockets and Rusty Star Shipyards
  NetKAN/RustyStarRockets.frozen
  NetKAN/RustyStarRockets.netkan
  NetKAN/RustyStarShipyards.netkan
Labels: Mod-request, Pull request

#9574 Names and authors for ASET IVA adoptions
  NetKAN/MK12PodIVAReplacementbyASET.netkan
  NetKAN/Mk1CockpitIVAReplbyASET.netkan
  NetKAN/Mk1LanderCanIVAReplbyASET.netkan
Labels: Easy, Pull request

#9575 Mark HyperDriveMod as version independent
  NetKAN/HyperDriveMod.netkan
Labels: Pull request, Fix compatibility

#9576 Update Kerbulator compatibility
  NetKAN/Kerbulator.netkan
Labels: Easy, Fix compatibility

#9577 Fix HLS-Project install
  NetKAN/HLS-Project.netkan
Labels: Fix install, Pull request

#9581 Install crafts folder to GameData for BDArmoryForRunwayProject
  NetKAN/BDArmoryForRunwayProject.netkan
Labels: Easy, Fix install, Pull request

#9573 Switch ASETAgency to new fork
  NetKAN/ASETAgency.netkan
Labels: Mod-request, Pull request

#9582 Add missing HabTech2 dependencies
  NetKAN/HabTech2.netkan
  NetKAN/HabTechRobotics.netkan
Labels: Fix relationships, Pull request

#9586 Switch HabTechRobotics from bundled to depends for ShuttleOrbiterConstructionKit
  NetKAN/ShuttleOrbiterConstructionKit.netkan
Labels: Fix relationships, Fix install, Pull request, Bug
