Repository KSP-CKAN/NetKAN, pull requests merged in 2024-07, with the labels that each got.

#10073 Switch Bureaucracy to new adopting fork
  NetKAN/Bureaucracy.netkan
Labels: Mod request

#10074 Update QuackPack dependencies
  NetKAN/QuackPack.netkan
Labels: Fix relationships

#10075 Fix VertexHeightOblateAdvanced install path
  NetKAN/VertexHeightOblateAdvanced.netkan
Labels: In progress, Fix install, Waiting for new mod release

#10084 Update WildBlue-PlayMode-CRP.netkan
  NetKAN/WildBlue-PlayMode-CRP.netkan
Labels: Fix install

#10091 Fix RustyStarRockets install path
  NetKAN/RustyStarRockets.netkan
Labels: Fix install

#10092 Fix RustyStarShipyards install
  NetKAN/RustyStarShipyards.netkan
Labels: Fix install

#10093 trim relationships for RustyStarRockets
  NetKAN/RustyStarRockets.netkan
  NetKAN/RustyStarShipyards.netkan
Labels: Fix relationships

#10094 Add my Mk2Rebalance mod
  NetKAN/Mk2Rebalance.netkan
Labels: Mod request

#10099 Fix SIMPLEXResources versioning
  NetKAN/SIMPLEXResources.netkan
Labels: Fix versioning

#10101 Avalanche: Add suggestions
  NetKAN/AvalanchePlumes.netkan
Labels: Fix relationships

#10103 Fixes for G-Effects
  NetKAN/G-Effects.frozen
  NetKAN/G-Effects.netkan
Labels: Fix versioning

#10110 Clean up replaced-by in frozen netkans
  NetKAN/KeminiResearchProgram.frozen
  NetKAN/KerbalEnvironmentalEffectsStudy.frozen
  NetKAN/KerbalLifeScience.frozen
  NetKAN/NehemiahInc-Complete.frozen
  NetKAN/NehemiahMultiPurposeParts.frozen
  NetKAN/NehemiahScienceCommon.frozen
  NetKAN/OrbitalMaterialScience.frozen
Labels: Easy, Bug

#10117 Fix NeidonPlus install again again
  NetKAN/NeidonPlus.netkan
Labels: Fix install

#10114 ColdJsHeliCarrier: add suggested mods
  NetKAN/ColdJsHeliCarrier.netkan
Labels: Fix relationships

#10129 Add RSS-Origin
  NetKAN/RSSOrigin-CelestialsPack-Centaurs.netkan
  NetKAN/RSSOrigin-CelestialsPack-Comets.netkan
  NetKAN/RSSOrigin-CelestialsPack-InterstellarObjects.netkan
  NetKAN/RSSOrigin-CelestialsPack-JupiterMoons.netkan
  NetKAN/RSSOrigin-CelestialsPack-JupiterTrojans.netkan
  NetKAN/RSSOrigin-CelestialsPack-MainBeltAsteroids.netkan
  NetKAN/RSSOrigin-CelestialsPack-MarsCrossers.netkan
  NetKAN/RSSOrigin-CelestialsPack-NearEarthObjects.netkan
  NetKAN/RSSOrigin-CelestialsPack-NeptuneMoons.netkan
  NetKAN/RSSOrigin-CelestialsPack-PlutoMoons.netkan
  NetKAN/RSSOrigin-CelestialsPack-SaturnMoons.netkan
  NetKAN/RSSOrigin-CelestialsPack-TransNeptunianObjects.netkan
  NetKAN/RSSOrigin-CelestialsPack-UranusMoons.netkan
  NetKAN/RSSOrigin-GalaxyTex-16k.netkan
  NetKAN/RSSOrigin-GalaxyTex-32k.netkan
  NetKAN/RSSOrigin-GalaxyTex-64k.netkan
  NetKAN/RSSOrigin-GalaxyTex-8k.netkan
  NetKAN/RSSOrigin-JSUNrings.netkan
  NetKAN/RSSOrigin.netkan
Labels: Mod request

#10141 TexturesUnlimited: unfreeze and point at new repo
  NetKAN/TexturesUnlimited.frozen
  NetKAN/TexturesUnlimited.netkan
Labels: Mod enhancement

#10142 Halloween: fix relationships, add tags
  NetKAN/Halloween.netkan
Labels: Fix relationships
