Repository KSP-CKAN/NetKAN, pull requests merged in 2024-10, with the labels that each got.

#10236 Bump CelestialHarmony epoch
  NetKAN/CelestialHarmony.netkan
Labels: Fix versioning

#10239 Add KSPCommunityPartModules to CKAN
  NetKAN/KSPCommunityPartModules.netkan
Labels: Mod request

#10240 Freeze duplicate OrdinaryKonstructionCo
  NetKAN/OrdinaryKonstruction.netkan
  NetKAN/OrdinaryKonstructionCo.frozen
Labels: Freeze

#10245 Fix SimpleRepaint version specific depends
  NetKAN/SimpleRepaint.netkan
Labels: Fix relationships

#10249 Added a .version file to LazyPainter
  NetKAN/LazyPainter.netkan
Labels: Fix compatibility

#10251 Add NGC5679-Skybox
  NetKAN/NGC5679-Skybox.netkan
Labels: Mod request

#10252 Add two more RecolorCollection mods
  NetKAN/RecolorCollection-ExtraDockingPorts.netkan
  NetKAN/RecolorCollection-MissingHistory.netkan
  NetKAN/RecolorCollection-NearFutureAeronautics.netkan
  NetKAN/RecolorCollection-NearFutureLaunchVehicles.netkan
  NetKAN/RecolorCollection-NearFuturePropulsion.netkan
  NetKAN/RecolorCollection-NearFutureSpacecraft.netkan
Labels: Mod request

#10250 Add SunkWorks
  NetKAN/SunkWorks.netkan
Labels: Mod request

#10256 Add conflicts with WildBlue play modes' provided names
  NetKAN/Buffalo-PlayMode-CRP.netkan
  NetKAN/Buffalo-PlayMode-ClassicStock.netkan
  NetKAN/DSEV-PlayMode-CRP.netkan
  NetKAN/DSEV-PlayMode-ClassicStock.netkan
  NetKAN/DSEV-PlayMode-Pristine.netkan
  NetKAN/Heisenberg-PlayMode-CRP.netkan
  NetKAN/Heisenberg-PlayMode-ClassicStock.netkan
  NetKAN/Heisenberg-PlayMode-Pristine.netkan
  NetKAN/Heisenberg-PlayMode-Simplified.netkan
  NetKAN/MOLE-PlayMode-CRP.netkan
  NetKAN/MOLE-PlayMode-ClassicStock.netkan
  NetKAN/MOLE-PlayMode-Pristine.netkan
  NetKAN/Pathfinder-PlayMode-CRP.netkan
  NetKAN/Pathfinder-PlayMode-ClassicStock.netkan
  NetKAN/Pathfinder-PlayMode-Pristine.netkan
  NetKAN/Pathfinder-PlayMode-Simplified.netkan
  NetKAN/WildBlue-PlayMode-CRP.netkan
  NetKAN/WildBlue-PlayMode-Pristine.netkan
  NetKAN/WildBlue-PlayMode-Simplified.netkan
Labels: Fix relationships

#10257 Freeze BrunosRocketEmporiumAndDesigns
  NetKAN/BrunosRocketEmporiumAndDesigns.frozen
Labels: Freeze

#10260 Add RSSOrigin-Less
  NetKAN/RSSOrigin-Less-Primary.netkan
  NetKAN/RSSOrigin-Less-Secondary.netkan
Labels: Mod request

#10265 Update ROEngines.netkan
  NetKAN/ROEngines.netkan
Labels: Fix relationships

#10269 Remove Deferred marking old Parallax versions as incompatible
  NetKAN/Deferred.netkan
Labels: Fix relationships
