Repository KSP-CKAN/NetKAN, pull requests merged in 2024-12, with the labels that each got.

#10313 Add StockAutoCutDrogues to CKAN
  NetKAN/StockAutoCutDrogues.netkan
Labels: Mod request

#10319 Coerce StarshipExpansionProject versioning into consistency
  NetKAN/StarshipExpansionProject.netkan
  NetKAN/StarshipExpansionProjectIVA.netkan
Labels: Fix versioning

#10323 Create LagrangeProjectRSS.netkan
  NetKAN/LagrangeProjectRSS.netkan
Labels: Mod request

#10324 Ignore prereleases for BetterRocketDesigns
  NetKAN/BetterRocketDesigns.netkan
Labels: Fix versioning

#10325 Update StarshipExpansionProject NetKAN
  NetKAN/StarshipExpansionProject.netkan
  NetKAN/StarshipExpansionProjectIVA.netkan
Labels: Blocked on CKAN feature

#10345 Fix ShineFix depends
  NetKAN/ShineFix.netkan
Labels: Fix relationships

#10347 Strategia dep for TourismOverhaul
  NetKAN/TourismOverhaul.netkan
Labels: Fix relationships
