Repository KSP-CKAN/NetKAN, pull requests merged in 2024-06, with the labels that each got.

#10039 Unfreeze and update SRBWaterfallEffects
  NetKAN/SRBWaterfallEffects.netkan
Labels: Blocked on mod author

#10045 Make NavUtilities forks mutually exclusive
  NetKAN/NavUtilitiesContinued.netkan
  NetKAN/NavUtilitiesUpdated.netkan
Labels: Fix relationships

#10047 Only install generic crafts for ModularLaunchPads
  NetKAN/ModularLaunchPads.netkan
Labels: Fix install

#10048 Add KopernicusExpansion dep to TechosStockPlanetRevamp
  NetKAN/TechosStockPlanetRevamp.netkan
Labels: Fix relationships

#10053 Unfreeze SigmaDimensions with new fork
  NetKAN/SigmaDimensions.frozen
  NetKAN/SigmaDimensions.netkan
Labels: Mod request, Easy

#10057 Add missing Lazarus dependencies
  NetKAN/Lazarus-Content.netkan
  NetKAN/Lazarus.netkan
Labels: Fix relationships

#10059 Fix AtomicTechIncJunkyards install
  NetKAN/AtomicTechIncJunkyards.netkan
Labels: Fix install

#10062 Remove unavailable dependency from KerbinSideRemasteredTLA
  NetKAN/KerbinSideRemasteredTLA.netkan
Labels: Fix relationships, Easy

#10061 Recommend Parallax for Lazarus
  NetKAN/Lazarus.netkan
Labels: Fix relationships, Easy

#10058 Update paths of stock scatterer configs for new scatterer version
  NetKAN/Scatterer-config.netkan
  NetKAN/Scatterer-sunflare.netkan
  NetKAN/Scatterer.netkan
Labels: Mod enhancement, In progress, Fix install, Waiting on PR creator

#10064 Update RSS-Adapter.netkan
  NetKAN/RSS-Adapter.netkan
Labels: Fix relationships

#10070 Update BetterKerbol relationships
  NetKAN/BetterKerbol.netkan
  NetKAN/BetterKerbolRescale.frozen
Labels: Fix relationships
