Repository KSP-CKAN/NetKAN, pull requests merged in 2024-03, with the labels that each got.

#9936 Add optional JNSQ rescale mods to stock (1x) and real (10x) size
  NetKAN/JNSQ-PartRebalancer-10x.netkan
  NetKAN/JNSQ-Rescale-10x.netkan
  NetKAN/JNSQ-Rescale-1x.netkan
Labels: Mod request, In progress

#9953 Update RocketMotorMenagerie compatibility
  NetKAN/RocketMotorMenagerie.netkan
Labels: Easy, Fix compatibility

#9959 SpaceY-Expanded: add dependency on SpaceY-Corp
  NetKAN/SpaceY-Expanded.netkan
Labels: Fix relationships, Blocked on dependency

#9954 Add RSS-Adapter
  NetKAN/RSS-Adapter.netkan
Labels: Mod request

#9963 Update RSS-Adapter relationships
  NetKAN/RSS-Adapter.netkan
Labels: Fix relationships

#9962 make WBI-playmode-USI provide ClassicStockResources-PlayMode
  NetKAN/WildBlue-PlayMode-USI.frozen
Labels: Fix relationships

#9964 De-meta CryoTanks to fix dependency issues
  NetKAN/CryoTanks-Core.netkan
  NetKAN/CryoTanks.netkan
  NetKAN/SkyhawkScienceSystem.netkan
Labels: Fix relationships

#9965 De-meta NearFutureSolar to fix dependency issues
  NetKAN/NearFutureSolar-Core.netkan
  NetKAN/NearFutureSolar.netkan
Labels: Fix relationships
