Repository KSP-CKAN/NetKAN, pull requests merged in 2024-08, with the labels that each got.

#10149 StockWaterfallEffects: change ksp max version to 1.12.5
  NetKAN/StockWaterfallEffects.netkan
Labels: Fix versioning

#10148 Add Deferred
  NetKAN/Deferred.netkan
Labels: Mod request

#10152 Install craft files for Pwings
  NetKAN/B9-PWings-Fork.netkan
Labels: Fix install

#10156 Resolve ColdJ Military Planes file conflicts
  NetKAN/ColdJsMilitaryPlanesF16.netkan
Labels: Fix install

#10160 Make ColdJsMilitaryPlanesF16 depend on ColdJsMilitaryPlanes
  NetKAN/ColdJsMilitaryPlanesF16.netkan
Labels: Fix relationships

#10161 Fix RSSOrigins compatibility
  NetKAN/RSSOrigin-CelestialsPack-Centaurs.netkan
  NetKAN/RSSOrigin-CelestialsPack-Comets.netkan
  NetKAN/RSSOrigin-CelestialsPack-InterstellarObjects.netkan
  NetKAN/RSSOrigin-CelestialsPack-JupiterMoons.netkan
  NetKAN/RSSOrigin-CelestialsPack-JupiterTrojans.netkan
  NetKAN/RSSOrigin-CelestialsPack-MainBeltAsteroids.netkan
  NetKAN/RSSOrigin-CelestialsPack-MarsCrossers.netkan
  NetKAN/RSSOrigin-CelestialsPack-NearEarthObjects.netkan
  NetKAN/RSSOrigin-CelestialsPack-NeptuneMoons.netkan
  NetKAN/RSSOrigin-CelestialsPack-PlutoMoons.netkan
  NetKAN/RSSOrigin-CelestialsPack-SaturnMoons.netkan
  NetKAN/RSSOrigin-CelestialsPack-TransNeptunianObjects.netkan
  NetKAN/RSSOrigin-CelestialsPack-UranusMoons.netkan
  NetKAN/RSSOrigin-GalaxyTex-16k.netkan
  NetKAN/RSSOrigin-GalaxyTex-32k.netkan
  NetKAN/RSSOrigin-GalaxyTex-64k.netkan
  NetKAN/RSSOrigin-GalaxyTex-8k.netkan
  NetKAN/RSSOrigin-JSUNrings.netkan
  NetKAN/RSSOrigin.netkan
Labels: Fix relationships, Easy, Fix compatibility

#10169 Changed dependencies TundraExploration.netkan
  NetKAN/TundraExploration.netkan
Labels: Fix relationships

#10174 Index VABOrganizer
  NetKAN/VABOrganizer.netkan
Labels: Mod request

#10175 Add Recolor Collection
  NetKAN/RecolorCollection-ExtraDockingPorts.netkan
  NetKAN/RecolorCollection-MissingHistory.netkan
  NetKAN/RecolorCollection-NearFuturePropulsion.netkan
  NetKAN/RecolorCollection-NearFutureSpacecraft.netkan
Labels: Mod request

#10176 Add RSSOrigin TopoRevamp
  NetKAN/RSSOrigin-TopoRevampConfigs.netkan
  NetKAN/RSSOrigin-TopoRevampTextures16k.netkan
  NetKAN/RSSOrigin-TopoRevampTextures4k.netkan
  NetKAN/RSSOrigin-TopoRevampTextures8k.netkan
Labels: Mod request

#10179 Split DKSalvage agency and flags into standalone module
  NetKAN/DKSalvageAgencyAndFlag.netkan
  NetKAN/RoveMateClassicTuneUp.netkan
  NetKAN/StructuralTubing.netkan
Labels: Fix license, Fix relationships

#10181 Set Mk-33's name to contain a dash
  NetKAN/Mk-33.netkan
Labels: Easy

#10184 Add SheepDog's VAB Organizer configs
  NetKAN/VABOrganizer-SheepDog.netkan
Labels: Mod request, Waiting for new mod release

#10189 Fix VABOrganizer-SheepDog install
  NetKAN/VABOrganizer-SheepDog.netkan
Labels: Fix install

#10198 VertexColorMapEmissive depends for KcalbelohSystem
  NetKAN/KcalbelohSystem.netkan
Labels: Fix relationships, Easy, Waiting for new mod release
