Repository KSP-CKAN/NetKAN, pull requests merged in 2024-11, with the labels that each got.

#10279 Add new RealAntennas dep
  NetKAN/RealAntennas.netkan
Labels: Fix relationships, Waiting for new mod release

#10282 Get JebFarAway from GitHub instead of SpaceDock
  NetKAN/JebFarAway.netkan
Labels: Mod enhancement, Easy

#10283 Remove release_status property from all netkans
  NetKAN/BDDMP.netkan
  NetKAN/DarkMultiPlayer.netkan
  NetKAN/KerbalEngineerRedux.netkan
  NetKAN/KerwisChinaAerospacePack.netkan
  NetKAN/Kopernicus.netkan
  NetKAN/PartOverhauls.netkan
  NetKAN/PlanetaryDiversity.netkan
  NetKAN/Scatterer-config.netkan
  NetKAN/Scatterer-sunflare.netkan
  NetKAN/Scatterer.netkan
  NetKAN/TextureReplacerReplaced.netkan
  NetKAN/USI-NuclearRockets.netkan
  NetKAN/kOSPropMonitor.netkan
Labels: Easy

#10287 StarshipExpansionProject: filter Spaces in case they move it
  NetKAN/StarshipExpansionProject.netkan
Labels: Fix install

#10298 MassEffectDrive: add harmony dependency
  NetKAN/MassEffectDrive.netkan
Labels: Fix relationships

#10299 Add BoringCrewServices to CKAN
  NetKAN/BoringCrewServices.netkan
Labels: Mod request

#10302 Vref for BLEAK
  NetKAN/BLEAK.netkan
Labels: Fix compatibility

#10303 Multi-part 16k texture pack for RSSOrigin
  NetKAN/RSSOrigin-TopoRevampTextures16k.netkan
  NetKAN/RSSOrigin-TopoRevampTextures16kPart2.netkan
Labels: Mod request

#10304 Remove trailing space from PhysicsRangeExtender name
  NetKAN/PhysicsRangeExtender.netkan
Labels: Easy

#10305 More flexible install for CollisionFXReUpdated
  NetKAN/CollisionFXReUpdated.netkan
Labels: Fix install

#10309 ContractConfigurator: add dependencies on harmony and modulemanager
  NetKAN/ContractConfigurator.netkan
Labels: Fix relationships
