Repository KSP-CKAN/NetKAN, pull requests merged in 2024-09, with the labels that each got.

#10203 Remove multi-hosting for three mods with bad repo versions
  NetKAN/BuranEnergia.netkan
  NetKAN/NoIntakeOcclusion.netkan
  NetKAN/ZeroMiniAVC.netkan
Labels: Fix versioning

#10173 Unfreeze Shabby at new fork, add Resurfaced
  NetKAN/Resurfaced.netkan
  NetKAN/Shabby.frozen
  NetKAN/Shabby.netkan
Labels: Mod request, Waiting for new mod release

#10207 Recommend Deferred for Resurfaced
  NetKAN/Resurfaced.netkan
Labels: Fix relationships

#10210 Add MassEffectDrive
  NetKAN/MassEffectDrive.netkan
Labels: Mod request, Waiting on PR creator

#10217 force_v for RasterPropMonitor-Core
  NetKAN/RasterPropMonitor-Core.netkan
Labels: Fix versioning

#10220 Add SterlingSystems family
  NetKAN/SterlingSystemsAgency.netkan
  NetKAN/SterlingSystemsElectrics.netkan
  NetKAN/SterlingSystemsElectricsFuelCell.netkan
  NetKAN/SterlingSystemsElectricsPhotoVoltaic.netkan
  NetKAN/SterlingSystemsEngines.netkan
  NetKAN/SterlingSystemsEnginesAntimatter.netkan
  NetKAN/SterlingSystemsEnginesFission.netkan
  NetKAN/SterlingSystemsEnginesFusion.netkan
  NetKAN/SterlingSystemsEnginesThermalNozzle.netkan
  NetKAN/SterlingSystemsTankage.netkan
  NetKAN/SterlingSystemsThermals.netkan
  NetKAN/SterlingSystemsThermalsExotic.netkan
  NetKAN/SterlingSystemsThermalsPower.netkan
  NetKAN/SterlingSystemsUtilities.netkan
  NetKAN/SterlingSystemsUtilitiesConstruction.netkan
  NetKAN/SterlingSystemsWorldPower.netkan
Labels: Mod request, In progress

#10221 Distantskies: depends on kopernicus expansion and VertexMitchellNetravaliHeightMap
  NetKAN/Distantskies.netkan
Labels: Fix relationships

#10222 KerbalInfinity depends on VertexMitchellNetravaliHeightMap
  NetKAN/KerbalInfinity.netkan
Labels: Fix relationships

#10224 freeiva: add newly supported mods
  NetKAN/FreeIva.netkan
Labels: Fix relationships

#10225 InterstellarFuelSwitch-Core only depends on tweakscale-redist
  NetKAN/InterstellarFuelSwitch-Core.netkan
Labels: Fix relationships

#10230 Advertise install filters in ZeroMiniAVC, fix BetterSRBs name
  NetKAN/BetterSRBs.netkan
  NetKAN/ZeroMiniAVC.netkan
Labels: Easy, Blocked on mod author
