Repository KSP-CKAN/NetKAN, pull requests merged in 2024-02, with the labels that each got.

#9910 Rename EVE stock configs to reduce user confusion
  NetKAN/EnvironmentalVisualEnhancements-HR.netkan
  NetKAN/EnvironmentalVisualEnhancements-LR.frozen
Labels: Discussion needed

#9921 Point KourageousTourists at Lisias' fork on spacedock
  NetKAN/KourageousTourists.netkan
Labels: Blocked on mod author

#9929 Add BetterRocketDesigns
  NetKAN/BetterRocketDesigns.netkan
Labels: Mod request, Waiting for new mod release

#9930 Set name for BetterRocketDesigns
  NetKAN/BetterRocketDesigns.netkan
Labels: Easy

#9935 Work around bad version on GitHub for CelestialRescale
  NetKAN/CelestialRescale.netkan
Labels: Fix versioning

#9942 Stable solution to IXSWarpship-Blueshift versioning
  NetKAN/IXSWarpship-Blueshift.netkan
Labels: Fix versioning
