Repository KSP-CKAN/NetKAN, pull requests merged in 2025-05, with the labels that each got.

#10521 Add netkan file for ISO 7010 Decals
  NetKAN/ISO-7010-Decals.netkan
Labels: Mod request

#10546 Create DockingModuleStageButtonHider.netkan
  NetKAN/DockingModuleStageButtonHider.netkan
Labels: Mod request

#10549 Add OPXFinalFrontierRibbons
  NetKAN/OPXFinalFrontierRibbons.netkan
Labels: Mod request

#10557 Update KolonyConstructs dependencies, multi-host
  NetKAN/KolonyConstructs.netkan
Labels: Fix relationships

#10563 Vref for KerbalChecklists
  NetKAN/KerbalChecklists.netkan
Labels: Fix compatibility

#10566 Remove two dependencies as not needed
  NetKAN/KerbalColonies.netkan
Labels: Fix relationships

#10572 Update NightShift requirements
  NetKAN/NightShift.netkan
Labels: Fix relationships

#10575 Changed suggests to recommends (Kerbal Colonies Core)
  NetKAN/KerbalColonies.netkan
Labels: Fix install

#10576 Add The Scattered Disk
  NetKAN/TheScatteredDisk.netkan
Labels: Mod request

#10578 New conflict for ETT
  NetKAN/ETT.netkan
Labels: Fix relationships

#10580 Add new CelestialHarmony submodule
  NetKAN/CelestialHarmony-Chaos.netkan
  NetKAN/CelestialHarmony.netkan
Labels: Mod enhancement, Fix relationships

#10581 Fix CelestialHarmony relationships
  NetKAN/CelestialHarmony-Chaos.netkan
  NetKAN/CelestialHarmony.netkan
Labels: Fix relationships
