Repository KSP-CKAN/NetKAN, pull requests merged in 2025-06, with the labels that each got.

#10595 Unfreeze HeapPadder.frozen with compatibility overrides
  NetKAN/HeapPadder.netkan
Labels: Fix compatibility

#10598 Add Proxima's Better Dres
  NetKAN/BetterDres.netkan
Labels: Mod request

#10602 Compatibility tweaks for a few mods
  NetKAN/GRAPEFRUIT.netkan
  NetKAN/Grounded.netkan
  NetKAN/MSP3000a.netkan
  NetKAN/RetroFuture.netkan
Labels: Easy, Fix compatibility

#10611 Add Missing Author to SSPX TU Recolor
  NetKAN/BoBSSPXTURecolor.netkan
Labels: Mod enhancement
