Repository KSP-CKAN/NetKAN, pull requests merged in 2025-08, with the labels that each got.

#10666 KerbalPowers Suite modifications
  NetKAN/KerbalPowersArmory.netkan
  NetKAN/KerbalPowersCore.netkan
  NetKAN/KerbalPowersInterstellar.netkan
Labels: Fix relationships, Fix install

#10660 Add kOS-Computer
  NetKAN/kOS-Computer.netkan
Labels: Mod request

#10669 Add Cosmic Serenity
  NetKAN/CosmicSerenity-Core.netkan
  NetKAN/CosmicSerenity-Hades.netkan
Labels: Mod request, In progress

#10671 Add LunaCompat
  NetKAN/LunaCompat.netkan
Labels: Mod request

#10686 Update 1ThousandSpecialPlanetPack-Textures install path
  NetKAN/1ThousandSpecialPlanetPack-Textures.netkan
Labels: Fix install

#10702 Add AnimatedAttachment to KerbalJointReinforcementContinued conflicts
  NetKAN/KerbalJointReinforcementContinued.netkan
Labels: Fix relationships

#10704 Add Promised Worlds
  NetKAN/PromisedWorldsCore.netkan
  NetKAN/PromisedWorldsDebdeb.netkan
Labels: Mod request

#10705 Fix name in the PromisedWorldsDebdeb.netkan
  NetKAN/PromisedWorldsDebdeb.netkan
Labels: Mod enhancement, Easy

#10707 Fix installation for Promised Worlds
  NetKAN/PromisedWorldsCore.netkan
  NetKAN/PromisedWorldsDebdeb.netkan
Labels: Mod enhancement

#10712 Get PromisedWorlds name, abstract, and author from SpaceDock
  NetKAN/PromisedWorldsCore.netkan
  NetKAN/PromisedWorldsDebdeb.netkan
Labels: Easy

#10716 Vrefs for PromisedWorlds
  NetKAN/PromisedWorldsCore.netkan
  NetKAN/PromisedWorldsDebdeb.netkan
Labels: Fix compatibility

#10717 Update KC metadata
  NetKAN/KerbalColonies.netkan
  NetKAN/KerbalColoniesExtraplanetaryLaunchpadsConfig.netkan
  NetKAN/KerbalColoniesIndustrialProcesses.netkan
Labels: Mod enhancement
