Repository KSP-CKAN/NetKAN, pull requests merged in 2025-01, with the labels that each got.

#10353 Update TourismOverhaul relationships
  NetKAN/TourismOverhaul.netkan
Labels: Fix relationships

#10376 Create Skopos
  NetKAN/Skopos.netkan
Labels: Mod request

#10381 Add license for TourismOverhaul
  NetKAN/TourismOverhaul.netkan
Labels: Fix license
