Repository KSP-CKAN/NetKAN, pull requests merged in 2025-07, with the labels that each got.

#10615 Unfreeze B9PartSwitch and switch to KSPModStewards fork
  NetKAN/B9PartSwitch.frozen
  NetKAN/B9PartSwitch.netkan
Labels: Mod request

#10619 Add FireflyAPI dep to Blueshift
  NetKAN/Blueshift.netkan
Labels: Fix relationships

#10627 Add AsteroidSpawnLimiter v1.0.0 — Limits untracked asteroids and comets
  NetKAN/AsteroidSpawnLimiter.netkan
Labels: Mod request

#10634 Extract ChemicalExotics from ChemicalPropulsion
  NetKAN/ChemicalExotics.netkan
Labels: Mod enhancement, Fix install

#10635 Fix RestockWaterfallExpansion install
  NetKAN/RestockWaterfallExpansion.netkan
Labels: Fix install

#10637 Unfreeze PortraitStats
  NetKAN/CommunityTraitIcons.frozen
  NetKAN/CommunityTraitIcons.netkan
  NetKAN/PortraitStats.frozen
  NetKAN/PortraitStats.netkan
Labels: Mod request

#10642 Unfreeze Impact!
  NetKAN/Impact.frozen
  NetKAN/Impact.netkan
Labels: Mod request

#10652 Move ProceduralParts relationships to internal ckan
  NetKAN/ProceduralParts.netkan
Labels: Fix relationships, Fix versioning
