Repository KSP-CKAN/NetKAN, pull requests merged in 2025-04, with the labels that each got.

#10476 Fixes #10474: KerbinSideRemasteredGAP: add dependencies on StockalikeStructures and KerbinsideCore
  NetKAN/KerbinSideRemasteredGAP.netkan
Labels: Fix relationships, Waiting for new mod release

#10477 KSPBurst: add compiler as a new package
  NetKAN/KSPBurst-Lite.netkan
  NetKAN/KSPBurst.netkan
Labels: Fix install

#10480 Remove KSPCommunityFixes conflict from PersistentRotationUpgraded
  NetKAN/PersistentRotationUpgraded.netkan
Labels: Fix relationships

#10483 KeridianDynamicsVesselAssembly fixes
  NetKAN/KeridianDynamicsVesselAssembly.netkan
Labels: Fix relationships

#10484 Add AutoVesselRenamer
  NetKAN/AutoVesselRenamer.netkan
Labels: Mod request, Blocked on mod author, Waiting for new mod release

#10486 Set MinorPlanetsExpansion resources.homepage
  NetKAN/MinorPlanetsExpansion.netkan
Labels: Easy

#10490 Unfreeze modules with internal .ckan files
  NetKAN/KerbalChangelog.netkan
  NetKAN/PlanningNode.netkan
Labels: Easy, Freeze

#10491 Add BreakingGround-DLC dep for HabTechRobotics
  NetKAN/HabTechRobotics.netkan
Labels: Fix relationships, Easy

#10492 Make KerbalChecklists depend on ClickThroughBlocker
  NetKAN/KerbalChecklists.netkan
Labels: Fix relationships

#10493 WildBlueTools Retirement
  NetKAN/ClassicStockResources-PlayMode-ClassicStock.frozen
  NetKAN/DSEV-PlayMode-CRP.frozen
  NetKAN/DSEV-PlayMode-ClassicStock.frozen
  NetKAN/DSEV-PlayMode-Pristine.frozen
  NetKAN/DSEV.netkan
  NetKAN/FlyingSaucers.netkan
  NetKAN/Heisenberg-PlayMode-CRP.frozen
  NetKAN/Heisenberg-PlayMode-ClassicStock.frozen
  NetKAN/Heisenberg-PlayMode-Pristine.frozen
  NetKAN/Heisenberg-PlayMode-Simplified.frozen
  NetKAN/Heisenberg.netkan
  NetKAN/MOLE.netkan
  NetKAN/Pathfinder-PlayMode-CRP.frozen
  NetKAN/Pathfinder-PlayMode-ClassicStock.frozen
  NetKAN/Pathfinder-PlayMode-Pristine.frozen
  NetKAN/Pathfinder-PlayMode-Simplified.frozen
  NetKAN/Pathfinder.netkan
  NetKAN/WBIProps.netkan
  NetKAN/WBIResources.netkan
  NetKAN/WBIScience.netkan
  NetKAN/WBIWidgets.netkan
  NetKAN/WildBlue-PlayMode-CRP.frozen
  NetKAN/WildBlue-PlayMode-ClassicStock.frozen
  NetKAN/WildBlue-PlayMode-Pristine.frozen
  NetKAN/WildBlue-PlayMode-Simplified.frozen
  NetKAN/WildBlueTools.frozen
Labels: Fix relationships

#10487 ASETProps: change supports to suggests; remove some
  NetKAN/ASETProps.netkan
Labels: Fix relationships

#10495 Make RationalResources hosting GitHub-only
  NetKAN/RationalResources.netkan
  NetKAN/RationalResourcesAluminium.netkan
  NetKAN/RationalResourcesBlacksmith.netkan
  NetKAN/RationalResourcesCompanion.netkan
  NetKAN/RationalResourcesELUtilities.netkan
  NetKAN/RationalResourcesJetFamily.netkan
  NetKAN/RationalResourcesKerbalism.netkan
  NetKAN/RationalResourcesKerbalismRF.netkan
  NetKAN/RationalResourcesNuclearFamily.netkan
  NetKAN/RationalResourcesParts.netkan
  NetKAN/RationalResourcesRCSFamily.netkan
  NetKAN/RationalResourcesSSPXRTanks.netkan
  NetKAN/RationalResourcesSquad.netkan
  NetKAN/RationalResourcesTACLS.netkan
Labels: Easy

#10497 Filter Resource dir out of AircraftCarrierAccessories
  NetKAN/AircraftCarrierAccessories.netkan
Labels: Fix install

#10498 Default install stanza for VuhrantiSystem
  NetKAN/VuhrantiSystem.netkan
Labels: Fix install

#10513 Update MinorPlanetsExpansion relationships and install
  NetKAN/MinorPlanetsExpansion.netkan
Labels: Fix relationships, Fix install

#10518 Filter two files out of Recoupler and RealPlume
  NetKAN/ReCoupler.netkan
  NetKAN/RealPlume.frozen
  NetKAN/RealPlume.netkan
Labels: Easy, Fix install
