Repository KSP-CKAN/NetKAN, pull requests merged in 2025-02, with the labels that each got.

#10397 Remove release status from TweakScaleRescaled auxiliary mods
  NetKAN/TweakScaleRescaled-Redist.netkan
  NetKAN/TweakScaleRescaled-SafetyNet.netkan
Labels: Fix versioning

#10400 TweakScaleRescaled - add conflict with TweakScaleCompanion-ReStockPlus
  NetKAN/TweakScaleRescaled.netkan
Labels: Fix relationships

#10401 Freeze modules with archives repositories
  NetKAN/H-II-H3-TransferVehicle.frozen
  NetKAN/ShuttlePayloadDeliverySystems.frozen
Labels: Freeze

#10404 Change mods that "support" b9partswitch to "suggest" instead
  NetKAN/DMTanks-SphericalTanks.netkan
  NetKAN/KeridianDynamicsVesselAssembly.netkan
  NetKAN/MoldaviteMachines.netkan
  NetKAN/SimpleConstruction.netkan
Labels: Fix relationships

#10409 Add KSPCommunityFixes conflict to PersistentRotationUpgraded
  NetKAN/PersistentRotationUpgraded.netkan
Labels: Fix relationships

#10422 Unfreeze SimpleFemaleKerbals
  NetKAN/SimpleFemaleKerbals.frozen
  NetKAN/SimpleFemaleKerbals.netkan
Labels: Easy

#10423 Fix FutureTechnologiesExpansion-FrontierAeronautics install
  NetKAN/FutureTechnologiesExpansion-FrontierAeronautics.netkan
Labels: Easy, Fix install
