Repository KSP-CKAN/NetKAN, pull requests merged in 2025-09, with the labels that each got.

#10719 Moving BonVoyage to Lisias's ownership
  NetKAN/BonVoyage.netkan
Labels: Mod request, In progress, Waiting on PR creator

#10724 XensPlanetCollectionRevived: move some supports to suggests
  NetKAN/XensPlanetCollectionRevived.netkan
Labels: Fix relationships

#10730 Vref for StockalikeMiningExtension
  NetKAN/StockalikeMiningExtension.netkan
Labels: Fix compatibility

#10739 Fix Proxima's Better Dres typo
  NetKAN/BetterDres.netkan
Labels: Mod enhancement

#10718 Handle bundled ScaledDecorator dep in Promised Worlds
  NetKAN/PromisedWorldsCore.netkan
Labels: Mod enhancement, Fix install

#10740 Drop SpaceDock support for PromisedWorlds
  NetKAN/PromisedWorldsCore.netkan
  NetKAN/PromisedWorldsDebdeb.netkan
Labels: Mod enhancement, Fix compatibility

#10743 Fix names in the Promised Worlds netkans
  NetKAN/PromisedWorldsCore.netkan
  NetKAN/PromisedWorldsDebdeb.netkan
Labels: Mod enhancement

#10746 Work around SCANsat dropping v prefix on GitHub
  NetKAN/SCANsat.netkan
Labels: Fix versioning

#10753 Changed author from Promised Worlds to Promised Worlds Dev Team in the LMPPW_Bases mod
  NetKAN/PWLMPBases.netkan
Labels: Mod enhancement

#10759 Add KSPCommunityFixes as a dependency to Promised Worlds
  NetKAN/PromisedWorldsCore.netkan
Labels: Mod enhancement
